/*

   Derby - Class org.apache.derbyBuild.asm.GeneratedBytecodeAsmJvm21Proof

   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to you under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

 */

package org.apache.derbyBuild.asm;

import java.io.InputStream;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import org.apache.derby.iapi.services.classfile.VMOpcode;
import org.apache.derby.iapi.services.compiler.ClassBuilder;
import org.apache.derby.iapi.services.compiler.JavaFactory;
import org.apache.derby.iapi.services.compiler.MethodBuilder;
import org.apache.derby.iapi.util.ByteArray;
import org.apache.derby.impl.services.bytecode.ExperimentalBytecodeJavaFactory;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;

/**
 * Permanent proof for the default generated-bytecode path after the ASM switch.
 *
 * <p>The old {@code generatedBytecodeJvm21Proof} records the inherited Derby
 * {@code ClassHolder} writer. This proof checks the new default path: the
 * production module uses the stable selector, the selector defaults to ASM when
 * no override is supplied, and the generated classfile is Java 21.</p>
 */
public final class GeneratedBytecodeAsmJvm21Proof {
    private static final String GENERATED_CLASS =
            "org.apache.derbyBuild.asm.generated.proof.GeneratedBytecodeAsmJvm21ProofClass";
    private static final String MODULE_PROPERTY = "derby.module.javaCompiler";
    private static final String SELECTOR_CLASS = ExperimentalBytecodeJavaFactory.class.getName();

    private GeneratedBytecodeAsmJvm21Proof() {
    }

    public static void main(String[] args) throws Exception {
        assertProductionModuleUsesSelector();

        String previousBackend = System.getProperty(ExperimentalBytecodeJavaFactory.BACKEND_PROPERTY);
        try {
            System.clearProperty(ExperimentalBytecodeJavaFactory.BACKEND_PROPERTY);
            assertDefaultBackendNameIsAsm();
            byte[] classBytes = generateThroughDefaultSelector();
            assertJava21Classfile(classBytes);
            assertClassReaderSeesGeneratedClass(classBytes);
            assertGeneratedClassRuns(classBytes);
        } finally {
            restoreProperty(ExperimentalBytecodeJavaFactory.BACKEND_PROPERTY, previousBackend);
        }

        System.out.println("Generated bytecode ASM JVM 21 proof passed: moduleCompiler=" + SELECTOR_CLASS
                + " backend=" + ExperimentalBytecodeJavaFactory.BACKEND_ASM
                + " classfileMajor=" + Opcodes.V21);
    }

    private static void assertProductionModuleUsesSelector() throws Exception {
        Properties properties = new Properties();
        try (InputStream stream = openModulesProperties()) {
            properties.load(stream);
        }
        String compiler = properties.getProperty(MODULE_PROPERTY);
        if (!SELECTOR_CLASS.equals(compiler)) {
            throw new AssertionError("Expected production " + MODULE_PROPERTY + " to use " + SELECTOR_CLASS
                    + " but was " + compiler);
        }
    }

    private static InputStream openModulesProperties() throws Exception {
        InputStream classpathStream = GeneratedBytecodeAsmJvm21Proof.class.getClassLoader()
                .getResourceAsStream("org/apache/derby/modules.properties");
        if (classpathStream != null) {
            return classpathStream;
        }

        Path sourceTreePath = Path.of("delosdb-engine", "src", "main", "java", "org", "apache", "derby",
                "modules.properties");
        if (Files.isRegularFile(sourceTreePath)) {
            return Files.newInputStream(sourceTreePath);
        }

        throw new AssertionError("Could not load org/apache/derby/modules.properties from classpath or "
                + sourceTreePath.toAbsolutePath());
    }

    private static void assertDefaultBackendNameIsAsm() {
        String selected = ExperimentalBytecodeJavaFactory.selectBackendName(new Properties());
        if (!ExperimentalBytecodeJavaFactory.BACKEND_ASM.equals(selected)) {
            throw new AssertionError("Expected default backend to be asm but was " + selected);
        }
    }

    private static byte[] generateThroughDefaultSelector() throws Exception {
        ExperimentalBytecodeJavaFactory selector = new ExperimentalBytecodeJavaFactory();
        selector.boot(false, new Properties());
        try {
            if (!ExperimentalBytecodeJavaFactory.BACKEND_ASM.equals(selector.selectedBackendName())) {
                throw new AssertionError("Booted selector should default to asm but selected "
                        + selector.selectedBackendName());
            }

            JavaFactory javaFactory = selector;
            String packageName = GENERATED_CLASS.substring(0, GENERATED_CLASS.lastIndexOf('.') + 1);
            String simpleName = GENERATED_CLASS.substring(GENERATED_CLASS.lastIndexOf('.') + 1);
            ClassBuilder classBuilder = javaFactory.newClassBuilder(null, packageName, Modifier.PUBLIC, simpleName,
                    "java.lang.Object");

            MethodBuilder constructor = classBuilder.newConstructorBuilder(Modifier.PUBLIC);
            constructor.callSuper();
            constructor.methodReturn();
            constructor.complete();

            MethodBuilder compute = classBuilder.newMethodBuilder(Modifier.PUBLIC | Modifier.STATIC, "int", "compute",
                    new String[] {"int"});
            compute.getParameter(0);
            compute.push(65);
            compute.callMethod(VMOpcode.INVOKESTATIC, "java.lang.Math", "max", "int", 2);
            compute.methodReturn();
            compute.complete();

            return copy(classBuilder.getClassBytecode());
        } finally {
            selector.stop();
        }
    }

    private static void assertJava21Classfile(byte[] classBytes) {
        if (classBytes.length < 8) {
            throw new AssertionError("Generated classfile is too small: " + classBytes.length);
        }
        int magic = ((classBytes[0] & 0xff) << 24)
                | ((classBytes[1] & 0xff) << 16)
                | ((classBytes[2] & 0xff) << 8)
                | (classBytes[3] & 0xff);
        if (magic != 0xcafebabe) {
            throw new AssertionError("Generated bytes do not start with CAFEBABE");
        }
        int major = ((classBytes[6] & 0xff) << 8) | (classBytes[7] & 0xff);
        if (major != Opcodes.V21) {
            throw new AssertionError("Expected Java 21 classfile major " + Opcodes.V21 + " but got " + major);
        }
    }

    private static void assertClassReaderSeesGeneratedClass(byte[] classBytes) {
        String actualName = new ClassReader(classBytes).getClassName().replace('/', '.');
        if (!GENERATED_CLASS.equals(actualName)) {
            throw new AssertionError("ClassReader saw " + actualName + " instead of " + GENERATED_CLASS);
        }
    }

    private static void assertGeneratedClassRuns(byte[] classBytes) throws Exception {
        Class<?> generated = new GeneratedLoader().define(GENERATED_CLASS, classBytes);
        Method method = generated.getMethod("compute", int.class);
        Object value = method.invoke(null, 7);
        if (!Integer.valueOf(65).equals(value)) {
            throw new AssertionError("Expected compute(7) to return 65 but got " + value);
        }
    }

    private static byte[] copy(ByteArray byteArray) {
        byte[] result = new byte[byteArray.getLength()];
        System.arraycopy(byteArray.getArray(), byteArray.getOffset(), result, 0, byteArray.getLength());
        return result;
    }

    private static void restoreProperty(String key, String previous) {
        if (previous == null) {
            System.clearProperty(key);
        } else {
            System.setProperty(key, previous);
        }
    }

    private static final class GeneratedLoader extends ClassLoader {
        private GeneratedLoader() {
            super(GeneratedBytecodeAsmJvm21Proof.class.getClassLoader());
        }

        private Class<?> define(String name, byte[] bytes) {
            return defineClass(name, bytes, 0, bytes.length);
        }
    }
}
