/*

   Derby - Class org.apache.derby.impl.sql.execute.DelosTableScanResultSet

   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to you under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

 */

package org.apache.derby.impl.sql.execute;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import io.github.ggeorg.delosdb.engine.extension.storage.versioned.sql.DelosNativeTableRegistry;
import org.apache.derby.iapi.sql.execute.CursorResultSet;
import org.apache.derby.iapi.sql.execute.ExecPreparedStatement;
import org.apache.derby.iapi.sql.execute.ExecRow;
import org.apache.derby.iapi.sql.execute.ExecRowBuilder;
import org.apache.derby.iapi.sql.execute.NoPutResultSet;
import org.apache.derby.iapi.sql.dictionary.ColumnDescriptor;
import org.apache.derby.iapi.sql.dictionary.TableDescriptor;
import org.apache.derby.iapi.store.access.Qualifier;
import org.apache.derby.iapi.store.types.DelosPredicate;
import org.apache.derby.iapi.store.types.DelosPredicateOperator;
import org.apache.derby.iapi.store.types.DelosProjection;
import org.apache.derby.iapi.store.types.DelosRow;
import org.apache.derby.iapi.store.types.DelosRowIdentity;
import org.apache.derby.iapi.store.types.DelosScan;
import org.apache.derby.iapi.store.types.StoreDataValue;
import org.apache.derby.iapi.types.DataValueDescriptor;
import org.apache.derby.iapi.types.Orderable;
import org.apache.derby.iapi.types.RowLocation;
import org.apache.derby.impl.services.storetypes.EngineMvccTableAccess;
import org.apache.derby.impl.services.storetypes.EngineStoreRowLocationBridge;
import org.apache.derby.shared.common.error.StandardException;

/**
 * Delos table-scan result set for the native Phase F execution seam.
 *
 * <p>F3.2 introduced this class as an honest skeleton.  F4 keeps the same
 * generated bytecode shape and replaces the sentinel, under a separate proof
 * property, with the first native MVCC SELECT-equality path:</p>
 *
 * <pre>
 * Qualifier[][]
 *   -> TableDescriptor column metadata
 *   -> DelosPredicate equality
 *   -> EngineMvccTableAccess.scan(...)
 *   -> Derby ExecRow materialization
 * </pre>
 */
final class DelosTableScanResultSet extends NoPutResultSetImpl
        implements CursorResultSet
{
    static final String SKELETON_BRANCH_PROPERTY =
            "delosdb.storage.phaseF32.delosTableScanSkeleton";

    static final String NATIVE_SELECT_EQUALITY_PROPERTY =
            "delosdb.storage.phaseF4.nativeMvccSelectEquality";

    static final String NATIVE_RANGE_PREDICATES_PROPERTY =
            "delosdb.storage.phaseG1.nativeRangePredicates";

    static final String NATIVE_BETWEEN_PREDICATES_PROPERTY =
            "delosdb.storage.phaseG2.nativeBetweenPredicates";

    static final String NATIVE_SELECT_ALL_PROPERTY =
            "delosdb.storage.phaseG3.nativeSelectAll";

    static final String NATIVE_COUNT_AGGREGATE_PROPERTY =
            "delosdb.storage.phaseG4.nativeCountAggregate";

    static final String SKELETON_REACHED_MESSAGE =
            "DelosTableScanResultSet skeleton reached; F4 must implement real MVCC scan materialization";

    static final String NATIVE_SELECT_REACHED_MESSAGE =
            "DelosTableScanResultSet native MVCC SELECT equality reached";

    private final TableScanResultSetParameters params;
    private final DelosTableScanProviderLookup.Result providerLookup;
    private final boolean nativeSelectEquality;
    private final boolean nativeSelectAll;
    private DelosNativeTableRegistry.NativeExecutionTableAccess nativeAccess;
    private DelosScan scan;
    private DelosRow currentDelosRow;
    private final RowLocation syntheticMutationRowLocation = EngineStoreRowLocationBridge.newEngineRowLocation();

    private DelosTableScanResultSet(
            TableScanResultSetParameters params,
            DelosTableScanProviderLookup.Result providerLookup,
            boolean nativeSelectEquality,
            boolean nativeSelectAll)
    {
        super(params.activation,
                params.resultSetNumber,
                params.optimizerEstimatedRowCount,
                params.optimizerEstimatedCost);
        this.params = params;
        this.providerLookup = providerLookup;
        this.nativeSelectEquality = nativeSelectEquality;
        this.nativeSelectAll = nativeSelectAll;
        recordConstructorTime();
    }

    static Optional<NoPutResultSet> createIfEnabled(TableScanResultSetParameters params)
            throws StandardException
    {
        boolean nativeSelectAllEnabled = Boolean.getBoolean(NATIVE_SELECT_ALL_PROPERTY)
                || Boolean.getBoolean(NATIVE_COUNT_AGGREGATE_PROPERTY);
        boolean nativePredicateScanEnabled = nativeSelectAllEnabled
                || Boolean.getBoolean(NATIVE_SELECT_EQUALITY_PROPERTY)
                || Boolean.getBoolean(NATIVE_RANGE_PREDICATES_PROPERTY)
                || Boolean.getBoolean(NATIVE_BETWEEN_PREDICATES_PROPERTY);
        boolean skeletonEnabled = Boolean.getBoolean(SKELETON_BRANCH_PROPERTY);
        if (!nativePredicateScanEnabled && !skeletonEnabled) {
            return Optional.empty();
        }

        Optional<DelosTableScanProviderLookup.Result> lookup =
                DelosTableScanProviderLookup.find(params.activation, params.tableName);
        if (lookup.isEmpty() || lookup.get().isDefaultStorageProvider()) {
            return Optional.empty();
        }

        return Optional.of(new DelosTableScanResultSet(
                params,
                lookup.get(),
                nativePredicateScanEnabled,
                nativeSelectAllEnabled));
    }

    @Override
    public void openCore() throws StandardException
    {
        beginTime = getCurrentTimeMillis();
        try {
            if (isOpen) {
                throw StandardException.plainWrapException(
                        new IllegalStateException("DelosTableScanResultSet is already open"));
            }
            if (!nativeSelectEquality) {
                throw StandardException.plainWrapException(
                        new UnsupportedOperationException(SKELETON_REACHED_MESSAGE));
            }

            TableDescriptor tableDescriptor = tableDescriptor();
            List<DelosPredicate> filters = scanPredicates(tableDescriptor, nativeSelectAll);
            nativeAccess = DelosNativeResultSetSupport.openNativeTableAccess(tableDescriptor, providerLookup);
            requireSnapshotIsolation(nativeAccess.tableAccess());
            scan = nativeAccess.tableAccess().scan(
                    nativeAccess.context(),
                    filters,
                    DelosProjection.all());
            isOpen = true;
            finished = false;
            numOpens++;
        } catch (SQLException e) {
            abortNativeAccess(e);
            throw StandardException.plainWrapException(e);
        } catch (RuntimeException e) {
            abortNativeAccess(e);
            throw StandardException.plainWrapException(e);
        } catch (StandardException e) {
            abortNativeAccess(e);
            throw e;
        } finally {
            openTime += getElapsedMillis(beginTime);
        }
    }

    @Override
    public ExecRow getNextRowCore() throws StandardException
    {
        beginTime = getCurrentTimeMillis();
        try {
            if (!isOpen || scan == null) {
                return null;
            }
            if (!scan.next()) {
                currentDelosRow = null;
                clearCurrentRow();
                finished = true;
                return null;
            }

            ExecRow row = newResultRow();
            currentDelosRow = scan.row();
            materialize(currentDelosRow, row);
            rowsSeen++;
            setCurrentRow(row);
            return row;
        } finally {
            nextTime += getElapsedMillis(beginTime);
        }
    }

    @Override
    public void close() throws StandardException
    {
        beginTime = getCurrentTimeMillis();
        StandardException failure = null;
        try {
            if (scan != null) {
                try {
                    scan.close();
                } catch (RuntimeException e) {
                    failure = StandardException.plainWrapException(e);
                } finally {
                    scan = null;
                }
            }
            if (nativeAccess != null) {
                try {
                    nativeAccess.close();
                } catch (SQLException e) {
                    StandardException wrapped = StandardException.plainWrapException(e);
                    if (failure == null) {
                        failure = wrapped;
                    } else {
                        failure.addSuppressed(wrapped);
                    }
                } finally {
                    nativeAccess = null;
                }
            }
            currentDelosRow = null;
            clearCurrentRow();
            super.close();
        } finally {
            closeTime += getElapsedMillis(beginTime);
        }
        if (failure != null) {
            throw failure;
        }
    }

    @Override
    public long getTimeSpent(int type)
    {
        return constructorTime + openTime + nextTime + closeTime;
    }

    @Override
    public int getScanIsolationLevel()
    {
        return params.isolationLevel;
    }

    @Override
    public RowLocation getRowLocation() throws StandardException
    {
        return syntheticMutationRowLocation;
    }

    @Override
    public ExecRow getCurrentRow() throws StandardException
    {
        return currentRow;
    }

    String tableNameForTesting()
    {
        return params.tableName;
    }

    String storageProviderNameForTesting()
    {
        return providerLookup.storageProviderName();
    }


    DelosTableScanProviderLookup.Result providerLookupForMutation()
    {
        return providerLookup;
    }

    TableDescriptor tableDescriptorForNativeRegistry() throws StandardException
    {
        return tableDescriptor();
    }

    List<DelosPredicate> equalityPredicatesForNativeMutation()
            throws StandardException
    {
        return equalityPredicates(tableDescriptor());
    }

    DelosRowIdentity currentDelosRowIdentityForNativeMutation() throws StandardException
    {
        if (currentDelosRow == null) {
            throw StandardException.plainWrapException(new IllegalStateException(
                    "No current delos_mvcc row identity is available for native mutation"));
        }
        return currentDelosRow.rowIdentity().orElseThrow(() ->
                new IllegalStateException("Native delos_mvcc scan row has no DelosRowIdentity"));
    }

    List<Object> currentDelosNativeValuesForNativeMutation() throws StandardException
    {
        if (currentDelosRow == null) {
            throw StandardException.plainWrapException(new IllegalStateException(
                    "No current delos_mvcc row values are available for native mutation"));
        }
        List<Object> nativeValues = new ArrayList<>(currentDelosRow.values().size());
        for (StoreDataValue value : currentDelosRow.values()) {
            nativeValues.add(EngineMvccTableAccess.nativeValue(value));
        }
        return List.copyOf(nativeValues);
    }

    static Optional<DelosTableScanResultSet> findIn(NoPutResultSet resultSet)
    {
        if (resultSet == null) {
            return Optional.empty();
        }
        if (resultSet instanceof DelosTableScanResultSet delosTableScan) {
            return Optional.of(delosTableScan);
        }
        if (resultSet instanceof ProjectRestrictResultSet projectRestrict) {
            return findIn(projectRestrict.source);
        }
        if (resultSet instanceof NormalizeResultSet normalize) {
            return findIn(normalize.source);
        }
        if (resultSet instanceof RowCountResultSet rowCount) {
            return findIn(rowCount.source);
        }
        if (resultSet instanceof ScrollInsensitiveResultSet scrollInsensitive) {
            return findIn(scrollInsensitive.source);
        }
        if (resultSet instanceof MaterializedResultSet materialized) {
            return findIn(materialized.source);
        }
        if (resultSet instanceof SortResultSet sort) {
            return findIn(sort.source);
        }
        if (resultSet instanceof IndexRowToBaseRowResultSet indexToBase) {
            return findIn(indexToBase.source);
        }
        return Optional.empty();
    }

    private TableDescriptor tableDescriptor() throws StandardException
    {
        return DelosNativeResultSetSupport.tableDescriptor(
                params.activation,
                providerLookup.schemaName(),
                providerLookup.tableName(),
                "Delos table scan");
    }

    private List<DelosPredicate> equalityPredicates(TableDescriptor tableDescriptor)
            throws StandardException
    {
        return predicates(tableDescriptor, false);
    }

    private List<DelosPredicate> scanPredicates(TableDescriptor tableDescriptor, boolean allowFullScan)
            throws StandardException
    {
        return predicates(tableDescriptor, true, allowFullScan);
    }

    private List<DelosPredicate> predicates(TableDescriptor tableDescriptor, boolean allowRangePredicates)
            throws StandardException
    {
        return predicates(tableDescriptor, allowRangePredicates, false);
    }

    private List<DelosPredicate> predicates(
            TableDescriptor tableDescriptor,
            boolean allowRangePredicates,
            boolean allowFullScan)
            throws StandardException
    {
        if (params.qualifiers == null || params.qualifiers.length == 0) {
            if (allowFullScan) {
                return List.of();
            }
            throw unsupported("Native delos_mvcc scan requires at least one pushed qualifier");
        }

        List<DelosPredicate> filters = new ArrayList<>();
        for (int term = 0; term < params.qualifiers.length; term++) {
            Qualifier[] termQualifiers = params.qualifiers[term];
            if (termQualifiers == null || termQualifiers.length == 0) {
                continue;
            }
            if (term > 0 && termQualifiers.length > 1) {
                throw unsupported("Native delos_mvcc scan does not support OR qualifier groups yet");
            }
            for (Qualifier qualifier : termQualifiers) {
                DelosPredicateOperator operator = predicateOperator(qualifier, allowRangePredicates);
                ColumnDescriptor column = tableDescriptor.getColumnDescriptor(qualifier.getColumnId() + 1);
                if (column == null) {
                    throw unsupported("Native delos_mvcc scan could not resolve qualifier column ordinal "
                            + qualifier.getColumnId());
                }
                StoreDataValue orderable = qualifier.getOrderable();
                if (operator == DelosPredicateOperator.EQUAL) {
                    filters.add(DelosPredicate.equalsTo(column.getColumnName(), orderable));
                } else {
                    filters.add(DelosPredicate.range(column.getColumnName(), operator, orderable));
                }
            }
        }
        if (filters.isEmpty() && !allowFullScan) {
            throw unsupported("Native delos_mvcc scan requires at least one pushed qualifier");
        }
        return List.copyOf(filters);
    }

    private static DelosPredicateOperator predicateOperator(Qualifier qualifier, boolean allowRangePredicates)
            throws StandardException
    {
        DelosPredicateOperator operator = switch (qualifier.getOperator()) {
            case Orderable.ORDER_OP_EQUALS -> DelosPredicateOperator.EQUAL;
            case Orderable.ORDER_OP_LESSTHAN -> DelosPredicateOperator.LESS_THAN;
            case Orderable.ORDER_OP_LESSOREQUALS -> DelosPredicateOperator.LESS_THAN_OR_EQUAL;
            case Orderable.ORDER_OP_GREATERTHAN -> DelosPredicateOperator.GREATER_THAN;
            case Orderable.ORDER_OP_GREATEROREQUALS -> DelosPredicateOperator.GREATER_THAN_OR_EQUAL;
            default -> throw unsupported("Native delos_mvcc scan does not support Derby qualifier operator "
                    + qualifier.getOperator());
        };
        if (qualifier.negateCompareResult()) {
            operator = negatedOperator(operator);
        }
        if (!allowRangePredicates && operator != DelosPredicateOperator.EQUAL) {
            throw unsupportedMutationRange();
        }
        return operator;
    }

    private static DelosPredicateOperator negatedOperator(DelosPredicateOperator operator)
    {
        return switch (operator) {
            case EQUAL -> DelosPredicateOperator.NOT_EQUAL;
            case LESS_THAN -> DelosPredicateOperator.GREATER_THAN_OR_EQUAL;
            case LESS_THAN_OR_EQUAL -> DelosPredicateOperator.GREATER_THAN;
            case GREATER_THAN -> DelosPredicateOperator.LESS_THAN_OR_EQUAL;
            case GREATER_THAN_OR_EQUAL -> DelosPredicateOperator.LESS_THAN;
            default -> throw new IllegalArgumentException(
                    "Native delos_mvcc scan cannot negate predicate operator " + operator);
        };
    }

    private static StandardException unsupportedMutationRange()
    {
        return unsupported("Native delos_mvcc mutation scan only supports equality qualifiers");
    }


    private void abortNativeAccess(Throwable failure)
    {
        if (nativeAccess == null) {
            return;
        }
        try {
            DelosNativeResultSetSupport.abortNativeAccess(nativeAccess, failure);
        } finally {
            nativeAccess = null;
            scan = null;
        }
    }

    private ExecRow newResultRow() throws StandardException
    {
        ExecPreparedStatement preparedStatement = params.activation.getPreparedStatement();
        ExecRowBuilder builder = (ExecRowBuilder) preparedStatement.getSavedObject(params.resultRowTemplate);
        return builder.build(params.activation.getExecutionFactory());
    }

    private void materialize(DelosRow delosRow, ExecRow resultRow) throws StandardException
    {
        int columnCount = Math.min(resultRow.nColumns(), delosRow.values().size());
        for (int column = 1; column <= columnCount; column++) {
            DataValueDescriptor target = resultRow.getColumn(column);
            if (target == null) {
                continue;
            }
            Object nativeValue = EngineMvccTableAccess.nativeValue(delosRow.values().get(column - 1));
            setDerbyValue(target, nativeValue);
        }
    }

    private static void setDerbyValue(DataValueDescriptor target, Object nativeValue)
            throws StandardException
    {
        if (nativeValue == null) {
            target.setToNull();
            return;
        }
        if (nativeValue instanceof Integer integer) {
            target.setValue(integer.intValue());
            return;
        }
        if (nativeValue instanceof Long longValue) {
            target.setValue(longValue.longValue());
            return;
        }
        if (nativeValue instanceof String string) {
            target.setValue(string);
            return;
        }
        throw StandardException.plainWrapException(new IllegalArgumentException(
                "Unsupported native delos_mvcc value for Derby materialization: "
                        + nativeValue.getClass().getName()));
    }

    private static void requireSnapshotIsolation(EngineMvccTableAccess tableAccess) throws StandardException
    {
        if (!tableAccess.guarantees().contains(
                org.apache.derby.iapi.store.types.DelosTableGuarantee.SNAPSHOT_ISOLATION)) {
            throw StandardException.plainWrapException(new IllegalStateException(
                    "F4 native MVCC SELECT equality requires SNAPSHOT_ISOLATION guarantee"));
        }
    }

    private static StandardException unsupported(String message)
    {
        return StandardException.plainWrapException(new UnsupportedOperationException(message));
    }
}
