pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'delosdb'

include 'delosdb-osgi-stub'
include 'delosdb-commons'
include 'delosdb-runtime-api'
include 'delosdb-annotations'
include 'delosdb-spi'
include 'delosdb-derby-store-api'
include 'delosdb-storage-mvcc'
include 'delosdb-storage-derby'
include 'delosdb-engine'
include 'delosdb-client'
include 'delosdb-tools'
include 'delosdb-runner'
include 'delosdb-optionaltools'
include 'delosdb-server'
include 'delosdb-tests'
include 'delosdb-pptesting'
include 'delosdb-storeless'
include 'delosdb-demos'
include 'delosdb-locales'
include 'delosdb-buildtools'
