plugins {
    id 'base'
}

import org.gradle.api.tasks.compile.JavaCompile

version = rootProject.version
group = rootProject.group

def moduleName = 'io.github.ggeorg.delosdb.engine.kernel'
def sourceRoot = file('src/main/java')
def moduleClassDir = layout.buildDirectory.dir("classes/modules/${moduleName}")
def commonsModuleClassDir = rootProject.project(':delosdb-commons').layout.buildDirectory.dir('classes/modules/org.apache.derby.commons')
def spiModuleClassDir = rootProject.project(':delosdb-spi').layout.buildDirectory.dir('classes/spi')

tasks.register('compileDelosDbEngineKernel', JavaCompile) {
    dependsOn ':delosdb-commons:compileDerbyCommons', ':delosdb-spi:compileDelosDbSpi'
    source = fileTree(sourceRoot) { include '**/*.java' }
    destinationDirectory = moduleClassDir
    rootProject.ext.delosdbConfigureJavaCompile(delegate, [commonsModuleClassDir, spiModuleClassDir])
}

tasks.register('classes') {
    dependsOn 'compileDelosDbEngineKernel'
}

tasks.named('assemble') {
    dependsOn 'classes'
}

tasks.register('delosDbEngineKernelJar', Jar) {
    dependsOn 'compileDelosDbEngineKernel'
    archiveFileName = 'delosdb-engine-kernel.jar'
    destinationDirectory = rootProject.layout.buildDirectory.dir('libs')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from moduleClassDir
    from(rootProject.ext.delosdbLegalFiles) {
        into 'META-INF'
    }
    manifest {
        attributes rootProject.ext.delosdbRuntimeJarAttributes('DelosDB Engine Kernel')
    }
}

tasks.named('assemble') {
    dependsOn 'delosDbEngineKernelJar'
}

tasks.named('check') {
    dependsOn 'compileDelosDbEngineKernel'
}


def generatedClassSizeCatalogSource = rootProject.layout.buildDirectory.file('generated/sources/org.apache.derby.engine/org/apache/derby/iapi/services/cache/ClassSizeCatalogImpl.java')

tasks.register('compileDelosDbEngineKernelClassSizeCatalog', JavaCompile) {
    dependsOn 'compileDelosDbEngineKernel', ':delosdb-commons:compileDerbyCommons', ':delosdb-spi:compileDelosDbSpi', ':delosdb-engine:compileDerbyEngine', ':generateClassSizeCatalog'
    source = files(generatedClassSizeCatalogSource)
    destinationDirectory = moduleClassDir
    rootProject.ext.delosdbConfigureJavaCompile(delegate, [
            commonsModuleClassDir,
            moduleClassDir,
            spiModuleClassDir
    ])
}

tasks.named('classes') {
    dependsOn 'compileDelosDbEngineKernelClassSizeCatalog'
}

tasks.named('delosDbEngineKernelJar') {
    dependsOn 'compileDelosDbEngineKernelClassSizeCatalog'
}
