#!/usr/bin/env bash
set -euo pipefail

apply=0
case "${1:-}" in
  --apply)
    apply=1
    shift
    ;;
  --dry-run|"")
    ;;
  *)
    echo "usage: $0 [--dry-run|--apply]" >&2
    exit 2
    ;;
esac

if [[ ! -f settings.gradle || ! -f build.gradle || ! -d delosdb-engine ]]; then
  echo "Refusing to run outside the DelosDB repo root." >&2
  echo "Expected settings.gradle, build.gradle, and delosdb-engine/." >&2
  exit 1
fi

mode="DRY-RUN"
if [[ "$apply" -eq 1 ]]; then
  mode="APPLY"
fi

echo "DelosDB stale validation/artifact cleanup (${mode})"
echo "Repository: $(pwd)"
echo

remove_path() {
  local path="$1"
  local reason="$2"

  if [[ -e "$path" || -L "$path" ]]; then
    echo "remove: $path"
    echo "  reason: $reason"
    if [[ "$apply" -eq 1 ]]; then
      rm -rf -- "$path"
    fi
  else
    echo "skip:   $path"
    echo "  reason: not present"
  fi
}

# Build/generated artifacts that may exist after old Derby/Ant-era builds or bad snapshot overlays.
remove_path "classes" "top-level compiled class output; Gradle builds use build/ instead"
remove_path "classes.pptesting" "top-level package-private test class output; Gradle builds use build/ instead"
remove_path "generated" "top-level generated output; Gradle parser/resource generation writes under build/"
remove_path "jars" "top-level assembled jar output; Gradle publishes runtime jars under build/libs"
remove_path "derby.log" "runtime log generated by local Derby execution"

# macOS/archive junk from ZIPs created on macOS.
remove_path "__MACOSX" "macOS ZIP metadata directory"
remove_path ".DS_Store" "macOS Finder metadata file"

# A previously bad source snapshot/overlay can create a nested repo folder at ./delosdb.
# Remove it only when it clearly looks like a nested DelosDB repo, never just because a folder exists.
if [[ -d "delosdb" && -f "delosdb/settings.gradle" && -f "delosdb/build.gradle" && -d "delosdb/delosdb-engine" ]]; then
  remove_path "delosdb" "accidental nested DelosDB source snapshot under the repo root"
else
  echo "skip:   delosdb"
  echo "  reason: no accidental nested DelosDB repo detected"
fi

# Remove nested .DS_Store files explicitly, but do not touch source files.
while IFS= read -r ds_store; do
  [[ -n "$ds_store" ]] || continue
  if [[ "$ds_store" == "./.DS_Store" ]]; then
    continue
  fi
  echo "remove: ${ds_store#./}"
  echo "  reason: macOS Finder metadata file"
  if [[ "$apply" -eq 1 ]]; then
    rm -f -- "$ds_store"
  fi
done < <(find . -name .DS_Store -type f -print)

echo
if [[ "$apply" -eq 1 ]]; then
  echo "Cleanup applied."
else
  echo "Dry run only. Re-run with --apply to delete the listed paths."
fi
