#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/deprecated-api-cleanup"
REPORT_FILE="$REPORT_DIR/deprecated-api-cleanup-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

PRODUCTION_ROOTS=(
  "$ROOT_DIR/delosdb-client/src/main/java"
  "$ROOT_DIR/delosdb-commons/src/main/java"
  "$ROOT_DIR/delosdb-engine/src/main/java"
  "$ROOT_DIR/delosdb-optionaltools/src/main/java"
  "$ROOT_DIR/delosdb-runner/src/main/java"
  "$ROOT_DIR/delosdb-server/src/main/java"
  "$ROOT_DIR/delosdb-tools/src/main/java"
)

existing_roots=()
for root in "${PRODUCTION_ROOTS[@]}"; do
  [[ -d "$root" ]] && existing_roots+=("$root")
done

count_java_matches() {
  local pattern="$1"
  shift
  local roots=("$@")
  if [[ ${#roots[@]} -eq 0 ]]; then
    echo 0
    return
  fi
  {
    grep -R --include='*.java' -E "$pattern" "${roots[@]}" 2>/dev/null \
      | grep -Ev '^[^:]+:[[:space:]]*(//|/\*|\*)|^[[:space:]]*(//|/\*|\*)' \
      || true
  } | wc -l | tr -d ' '
}

write_java_matches() {
  local title="$1"
  local pattern="$2"
  shift 2
  {
    echo
    echo "## $title"
    echo
    if [[ $# -eq 0 ]]; then
      echo "No source roots found."
      return
    fi
    grep -R --include='*.java' -n -E "$pattern" "$@" 2>/dev/null \
      | sed "s#${ROOT_DIR}/##" \
      | grep -Ev '^[^:]+:[0-9]+:[[:space:]]*(//|/\*|\*)' \
      || true
  } >> "$REPORT_FILE"
}

string_buffer_input_stream_count="$(count_java_matches 'StringBufferInputStream' "${existing_roots[@]}")"
thread_stop_suspend_resume_count="$(count_java_matches '\.stop[[:space:]]*\(|\.suspend[[:space:]]*\(|\.resume[[:space:]]*\(' "${existing_roots[@]}")"
finalizer_count="$(count_java_matches 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\(' "${existing_roots[@]}")"
clob_file="$ROOT_DIR/delosdb-client/src/main/java/org/apache/derby/client/am/ClientClob.java"

cat > "$REPORT_FILE" <<EOF_REPORT
# Deprecated API Cleanup Audit

Generated by \`dev/deprecated-api-cleanup-audit.sh\`.

This report tracks Java 21 cleanup candidates in inherited Derby production code.
The current cleanup removes the deprecated non-locator CLOB byte stream helper
without changing the legacy low-eight-bit byte mapping expected by that path.

## Summary

| Area | Count |
|---|---:|
| Production StringBufferInputStream references | ${string_buffer_input_stream_count} |
| Production lifecycle stop/suspend/resume-looking calls | ${thread_stop_suspend_resume_count} |
| Production Object finalizer overrides | ${finalizer_count} |

## Non-locator CLOB stream compatibility note

\`ClientClob.reInitForNonLocator\` is legacy client/server compatibility code.
The replacement stream intentionally keeps the old byte mapping: each UTF-16
character is exposed as \`char & 0xff\`. This avoids replacing a deprecated API
with charset conversion that would silently change wire bytes for non-ASCII data.
EOF_REPORT

write_java_matches "Production StringBufferInputStream references" 'StringBufferInputStream' "${existing_roots[@]}"
write_java_matches "Production lifecycle stop/suspend/resume-looking calls" '\.stop[[:space:]]*\(|\.suspend[[:space:]]*\(|\.resume[[:space:]]*\(' "${existing_roots[@]}"
write_java_matches "Production Object finalizer overrides" 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\(' "${existing_roots[@]}"

if [[ "$VERIFY" == true ]]; then
  failed=false

  if [[ ! -f "$clob_file" ]]; then
    echo "Deprecated API cleanup audit failed: ClientClob.java not found." >&2
    failed=true
  fi

  if [[ "$string_buffer_input_stream_count" != "0" ]]; then
    echo "Deprecated API cleanup audit failed: production StringBufferInputStream references remain." >&2
    failed=true
  fi

  if [[ -f "$clob_file" ]]; then
    if ! grep -q 'LegacyStringByteInputStream' "$clob_file"; then
      echo "Deprecated API cleanup audit failed: ClientClob replacement stream is missing." >&2
      failed=true
    fi
    if ! grep -q '& 0xff' "$clob_file"; then
      echo "Deprecated API cleanup audit failed: ClientClob replacement does not document/preserve low-byte mapping." >&2
      failed=true
    fi
  fi

  if [[ "$failed" == true ]]; then
    echo "See $REPORT_FILE" >&2
    exit 1
  fi
fi

echo "Deprecated API cleanup audit written to $REPORT_FILE"
