#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/generated-bytecode-jvm21"
REPORT_FILE="$REPORT_DIR/generated-bytecode-jvm21-proof.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

rel() {
  local path="$1"
  printf '%s' "${path#${ROOT_DIR}/}"
}

required_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "Missing required file: $(rel "$path")" >&2
    return 1
  fi
}

first_line() {
  local path="$1"
  local pattern="$2"
  grep -n -E "$pattern" "$path" | head -1 || true
}

all_lines() {
  local path="$1"
  local pattern="$2"
  grep -n -E "$pattern" "$path" || true
}

constant_value() {
  local path="$1"
  local name="$2"
  awk -v name="$name" '
    $0 ~ name "[[:space:]]*=" {
      line=$0
      sub(/.*=[[:space:]]*/, "", line)
      sub(/[;[:space:]].*/, "", line)
      print line
      exit
    }
  ' "$path"
}

VM_DESCRIPTOR="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/iapi/services/classfile/VMDescriptor.java"
CLASS_HOLDER="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/iapi/services/classfile/ClassHolder.java"
BC_CLASS="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/services/bytecode/BCClass.java"
G_CLASS="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/services/bytecode/GClass.java"
STATEMENT_NODE="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/sql/compile/StatementNode.java"
EXPRESSION_CLASS_BUILDER="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/sql/compile/ExpressionClassBuilder.java"
DATABASE_CLASSES="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/services/reflect/DatabaseClasses.java"
REFLECT_CLASSES="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/services/reflect/ReflectClassesJava2.java"
REFLECT_LOADER="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/services/reflect/ReflectLoaderJava2.java"
REFLECT_GENERATED_CLASS="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/services/reflect/ReflectGeneratedClass.java"
BUILD_PROBE_SRC="$ROOT_DIR/delosdb-buildtools/src/main/java/org/apache/derbyBuild/GeneratedBytecodeVersionProbe.java"

required_files=(
  "$VM_DESCRIPTOR"
  "$CLASS_HOLDER"
  "$BC_CLASS"
  "$G_CLASS"
  "$STATEMENT_NODE"
  "$EXPRESSION_CLASS_BUILDER"
  "$DATABASE_CLASSES"
  "$REFLECT_CLASSES"
  "$REFLECT_LOADER"
  "$REFLECT_GENERATED_CLASS"
  "$BUILD_PROBE_SRC"
)

for file in "${required_files[@]}"; do
  required_file "$file"
done

major_value="$(constant_value "$VM_DESCRIPTOR" 'JAVA_CLASS_FORMAT_MAJOR_VERSION')"
minor_value="$(constant_value "$VM_DESCRIPTOR" 'JAVA_CLASS_FORMAT_MINOR_VERSION')"
magic_value="$(constant_value "$VM_DESCRIPTOR" 'JAVA_CLASS_FORMAT_MAGIC')"

probe_output=""
probe_status="not-run"
probe_class_dir="$ROOT_DIR/delosdb-buildtools/build/classes/build-tools"
commons_class_dir="$ROOT_DIR/delosdb-commons/build/classes/modules/org.apache.derby.commons"
engine_class_dir="$ROOT_DIR/delosdb-engine/build/classes/modules/org.apache.derby.engine"
probe_class="$probe_class_dir/org/apache/derbyBuild/GeneratedBytecodeVersionProbe.class"

if [[ -f "$probe_class" && -d "$commons_class_dir" && -d "$engine_class_dir" ]]; then
  if probe_output="$(java -cp "$probe_class_dir:$commons_class_dir:$engine_class_dir" org.apache.derbyBuild.GeneratedBytecodeVersionProbe 2>&1)"; then
    probe_status="passed"
  else
    probe_status="failed"
  fi
else
  probe_output="Compiled probe is not available yet. Run ./gradlew generatedBytecodeJvm21Proof to compile and execute it, or run :delosdb-buildtools:compileDerbyBuildTools first."
  probe_status="not-compiled"
fi

java_version="$(java -version 2>&1 | head -3 || true)"

cat > "$REPORT_FILE" <<EOF_REPORT
# Generated Bytecode JVM 21 Proof

Generated by \`dev/generated-bytecode-jvm21-proof.sh\`.

This report is a guardrail for JVM 21 modernization of Derby's inherited generated-class path. It records the current emitted classfile version and the source path from SQL statement generation to HotSpot class loading. It intentionally does not change Derby's bytecode generator.

## Current JVM

\`\`\`text
${java_version}
\`\`\`

## Current generated classfile constants

Source: \`$(rel "$VM_DESCRIPTOR")\`

| Constant | Value |
|---|---:|
| JAVA_CLASS_FORMAT_MAGIC | ${magic_value:-unknown} |
| JAVA_CLASS_FORMAT_MINOR_VERSION | ${minor_value:-unknown} |
| JAVA_CLASS_FORMAT_MAJOR_VERSION | ${major_value:-unknown} |

The current generated classfile target is therefore **${major_value:-unknown}.${minor_value:-unknown}**. Do not bump this directly to the Java 21 classfile version without verifier and generated-activation tests.

## Runtime header probe

Status: **${probe_status}**

\`\`\`text
${probe_output}
\`\`\`

The probe uses the same \`ClassHolder\` writer that Derby uses for generated bytecode and reads the first eight bytes of the emitted classfile stream: magic, minor version, and major version.

## Source trail: generated activation to JVM class

| Step | Source | Landmark |
|---:|---|---|
| 1 | \`$(rel "$STATEMENT_NODE")\` | SQL statement generation creates an activation class and calls \`generatingClass.getGeneratedClass(byteCode)\`. |
| 2 | \`$(rel "$EXPRESSION_CLASS_BUILDER")\` | \`ExpressionClassBuilder.getGeneratedClass()\` asks the class builder for bytecode and generated class loading. |
| 3 | \`$(rel "$BC_CLASS")\` | \`BCClass.getClassBytecode()\` completes the class and calls \`classHold.getFileFormat()\`. |
| 4 | \`$(rel "$CLASS_HOLDER")\` | \`ClassHolder.put()\` writes CAFEBABE, minor version, and major version. |
| 5 | \`$(rel "$G_CLASS")\` | \`GClass.getGeneratedClass()\` calls \`ClassFactory.loadGeneratedClass(...)\`. |
| 6 | \`$(rel "$DATABASE_CLASSES")\` | \`DatabaseClasses.loadGeneratedClass(...)\` delegates to \`loadGeneratedClassFromData(...)\`. |
| 7 | \`$(rel "$REFLECT_CLASSES")\` | \`ReflectClassesJava2.loadGeneratedClassFromData(...)\` routes generated classes to \`ReflectLoaderJava2\`. |
| 8 | \`$(rel "$REFLECT_LOADER")\` | \`ReflectLoaderJava2.loadGeneratedClass(...)\` calls \`defineClass(...)\` and \`resolveClass(...)\`. |
| 9 | \`$(rel "$REFLECT_GENERATED_CLASS")\` | \`ReflectGeneratedClass\` wraps the JVM class and caches generated entry methods. |

## Source evidence snippets

### VMDescriptor constants

\`\`\`text
$(all_lines "$VM_DESCRIPTOR" 'JAVA_CLASS_FORMAT_MAGIC|JAVA_CLASS_FORMAT_MAJOR_VERSION|JAVA_CLASS_FORMAT_MINOR_VERSION')
\`\`\`

### ClassHolder header writer

\`\`\`text
$(all_lines "$CLASS_HOLDER" 'JAVA_CLASS_FORMAT_MAGIC|putU2\(minor_version\)|putU2\(major_version\)|major_version|minor_version' | head -40)
\`\`\`

### Activation generation and loading path

\`\`\`text
$(first_line "$STATEMENT_NODE" 'GeneratedClass activationClass = generatingClass.getGeneratedClass')
$(first_line "$EXPRESSION_CLASS_BUILDER" 'cb.getClassBytecode\(\)|cb.getGeneratedClass\(\)')
$(first_line "$BC_CLASS" 'classHold.getFileFormat\(\)')
$(first_line "$G_CLASS" 'cf.loadGeneratedClass')
$(first_line "$DATABASE_CLASSES" 'loadGeneratedClassFromData')
$(first_line "$REFLECT_CLASSES" 'ReflectLoaderJava2.*loadGeneratedClass|loadGeneratedClass\(fullyQualifiedName, classDump\)')
$(first_line "$REFLECT_LOADER" 'defineClass|resolveClass')
\`\`\`

## JVM 21 modernization rule

Safe next work is measurement and dispatch cleanup. Unsafe next work is changing \`JAVA_CLASS_FORMAT_MAJOR_VERSION\` to a modern Java value without proving stack-map/verifier behavior for generated activation classes.
EOF_REPORT

if [[ "$VERIFY" == true ]]; then
  failed=false

  if [[ -z "$major_value" || -z "$minor_value" || -z "$magic_value" ]]; then
    echo "Generated bytecode JVM 21 proof failed: classfile constants were not found." >&2
    failed=true
  fi

  if [[ "$major_value" != "45" || "$minor_value" != "3" ]]; then
    echo "Generated bytecode JVM 21 proof failed: expected inherited Derby classfile version 45.3, found ${major_value}.${minor_value}. Update the modernization proof before changing generator semantics." >&2
    failed=true
  fi

  if ! grep -q 'out.putU4(VMDescriptor.JAVA_CLASS_FORMAT_MAGIC)' "$CLASS_HOLDER"; then
    echo "Generated bytecode JVM 21 proof failed: ClassHolder magic writer landmark changed." >&2
    failed=true
  fi

  if ! grep -q 'out.putU2(minor_version)' "$CLASS_HOLDER"; then
    echo "Generated bytecode JVM 21 proof failed: ClassHolder minor-version writer landmark changed." >&2
    failed=true
  fi

  if ! grep -q 'out.putU2(major_version)' "$CLASS_HOLDER"; then
    echo "Generated bytecode JVM 21 proof failed: ClassHolder major-version writer landmark changed." >&2
    failed=true
  fi

  if [[ "$probe_status" == "failed" ]]; then
    echo "Generated bytecode JVM 21 proof failed: runtime header probe failed." >&2
    echo "$probe_output" >&2
    failed=true
  fi

  if [[ "$failed" == true ]]; then
    echo "See $REPORT_FILE" >&2
    exit 1
  fi
fi

echo "Generated bytecode JVM 21 proof written to $REPORT_FILE"
