#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/generated-method-dispatch"
REPORT_FILE="$REPORT_DIR/generated-method-dispatch-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

rel() {
  local path="$1"
  printf '%s' "${path#${ROOT_DIR}/}"
}

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "Missing required file: $(rel "$path")" >&2
    return 1
  fi
}

require_pattern() {
  local path="$1"
  local pattern="$2"
  local label="$3"
  if ! grep -q -E "$pattern" "$path"; then
    echo "Missing expected dispatch landmark: $label in $(rel "$path")" >&2
    return 1
  fi
}

first_line() {
  local path="$1"
  local pattern="$2"
  grep -n -E "$pattern" "$path" | head -1 || true
}

all_lines() {
  local path="$1"
  local pattern="$2"
  grep -n -E "$pattern" "$path" || true
}

REFLECT_GENERATED_CLASS="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/services/reflect/ReflectGeneratedClass.java"
REFLECT_METHOD="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/impl/services/reflect/ReflectMethod.java"
GENERATED_BYTE_CODE="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/iapi/services/loader/GeneratedByteCode.java"
GENERATED_METHOD="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/iapi/services/loader/GeneratedMethod.java"

for file in "$REFLECT_GENERATED_CLASS" "$REFLECT_METHOD" "$GENERATED_BYTE_CODE" "$GENERATED_METHOD"; do
  require_file "$file"
done

cat > "$REPORT_FILE" <<EOF_REPORT
# Generated Method Dispatch Audit

Generated by dev/generated-method-dispatch-audit.sh.

This report tracks Derby's inherited generated-method dispatch path after the
small JVM 21 cleanup in ReflectGeneratedClass. The common generated activation
methods e0 through e9 still use direct calls. Less common generated methods still
use the reflective fallback. This overlay intentionally does not replace Derby's
code generator or generated activation contract.

## Source trail

| Area | Source | Landmark |
|---|---|---|
| Generated bytecode contract | $(rel "$GENERATED_BYTE_CODE") | Declares direct entrypoints e0 through e9. |
| Generated method abstraction | $(rel "$GENERATED_METHOD") | Runtime wrapper used by generated result-set/activation calls. |
| Dispatch cache and resolver | $(rel "$REFLECT_GENERATED_CLASS") | Caches resolved generated methods, preserves direct e0..e9 dispatch, and falls back to public zero-argument reflection. |
| Reflective fallback | $(rel "$REFLECT_METHOD") | Invokes generated non-direct methods through Method.invoke. |

## Current dispatch landmarks

### Direct generated entrypoints

~~~text
$(all_lines "$GENERATED_BYTE_CODE" 'Object[[:space:]]+e[0-9][[:space:]]*\(')
~~~

### Cache and direct-call resolution

~~~text
$(first_line "$REFLECT_GENERATED_CLASS" 'ConcurrentMap<String,GeneratedMethod>')
$(first_line "$REFLECT_GENERATED_CLASS" 'methodCache\.putIfAbsent')
$(first_line "$REFLECT_GENERATED_CLASS" 'isDirectCallName')
$(first_line "$REFLECT_GENERATED_CLASS" 'getJVMClass\(\)\.getMethod')
~~~

### Reflective fallback

~~~text
$(first_line "$REFLECT_METHOD" 'realMethod\.invoke')
$(first_line "$REFLECT_METHOD" 'InvocationTargetException')
~~~

## Verification note

This cleanup is deliberately small:

- direct e0..e9 calls remain the hot path;
- invalid names such as ex no longer risk array-index dispatch mistakes;
- the cache now uses putIfAbsent, so concurrent resolution keeps one canonical cached wrapper;
- the reflective fallback remains behavior-compatible and is not replaced by MethodHandle yet.

Future work may experiment with MethodHandle only after this dispatch path has dedicated runtime smoke coverage.
EOF_REPORT

if $VERIFY; then
  require_pattern "$REFLECT_GENERATED_CLASS" 'methodCache\.putIfAbsent' 'canonical concurrent method-cache insertion'
  require_pattern "$REFLECT_GENERATED_CLASS" 'isDirectCallName' 'bounded direct e0..e9 dispatch check'
  require_pattern "$REFLECT_GENERATED_CLASS" 'NO_PARAMETER_TYPES' 'explicit zero-argument reflection parameter array'
  require_pattern "$REFLECT_GENERATED_CLASS" 'getJVMClass\(\)\.getMethod\(simpleName, NO_PARAMETER_TYPES\)' 'zero-argument reflective fallback'
  require_pattern "$REFLECT_METHOD" 'realMethod\.invoke' 'reflective fallback still present'
fi

echo "Generated method dispatch audit written to $REPORT_FILE"
