#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/inherited-code-quality"
REPORT_FILE="$REPORT_DIR/legacy-derby-harness-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

HARNESS_DIR="$ROOT_DIR/delosdb-tests/src/test/java/org/apache/derbyTesting/functionTests/harness"
TEST_SRC="$ROOT_DIR/delosdb-tests/src/test/java"
TEST_BUILD_FILE="$ROOT_DIR/delosdb-tests/build.gradle"

relative() {
  local path="$1"
  printf '%s' "${path#${ROOT_DIR}/}"
}

count_lines() {
  wc -l | tr -d ' '
}

find_project_files() {
  find "$ROOT_DIR" \
    -path "$ROOT_DIR/.git" -prune -o \
    -path "$ROOT_DIR/.gradle" -prune -o \
    -path "$ROOT_DIR/.idea" -prune -o \
    -path "$ROOT_DIR/build" -prune -o \
    -path '*/build' -prune -o \
    "$@"
}

java_refs_outside_harness() {
  local pattern="$1"
  if [[ ! -d "$TEST_SRC" ]]; then
    return 0
  fi
  find "$TEST_SRC" \
    -path "$HARNESS_DIR" -prune -o \
    -name '*.java' -type f -print0 \
    | xargs -0 grep -n -E "$pattern" 2>/dev/null \
    | sed "s#${ROOT_DIR}/##" \
    | grep -Ev '^[^:]+:[0-9]+:[[:space:]]*(//|/\*|\*)' \
    || true
}

gradle_entrypoint_refs() {
  find_project_files \( -name '*.gradle' -o -name 'settings.gradle' -o -name 'gradle.properties' \) -type f -print0 \
    | xargs -0 grep -n -E 'org\.apache\.derbyTesting\.functionTests\.harness\.(RunSuite|RunTest)|mainClass[[:space:]]*=.*RunSuite|mainClass[[:space:]]*=.*RunTest|RunSuite\.class|RunTest\.class' 2>/dev/null \
    | sed "s#${ROOT_DIR}/##" \
    || true
}

shell_entrypoint_refs() {
  find_project_files \( -name '*.sh' -o -name '*.bash' \) -type f -print0 \
    | xargs -0 grep -n -E 'org\.apache\.derbyTesting\.functionTests\.harness\.(RunSuite|RunTest)|RunSuite\.class|RunTest\.class' 2>/dev/null \
    | sed "s#${ROOT_DIR}/##" \
    | grep -Ev 'dev/legacy-derby-harness-audit\.sh' \
    || true
}

listed_as_gradle_exclude() {
  local relative_source="$1"
  [[ -f "$TEST_BUILD_FILE" ]] && grep -Fq "'${relative_source}'" "$TEST_BUILD_FILE"
}

stale_adapter_files=()
required_bridge_files=()
legacy_launcher_files=()
quarantined_entrypoint_files=()
if [[ -d "$HARNESS_DIR" ]]; then
  while IFS= read -r -d '' file; do
    stale_adapter_files+=("$file")
  done < <(find "$HARNESS_DIR" -maxdepth 1 -type f \
    \( -name 'jdk*.java' -o -name 'ibm*.java' -o -name 'j9*.java' \) \
    -print0 | sort -z)

  for name in jvm.java currentjvm.java; do
    if [[ -f "$HARNESS_DIR/$name" ]]; then
      required_bridge_files+=("$HARNESS_DIR/$name")
    fi
  done

  for name in RunTest.java RunList.java NetServer.java; do
    if [[ -f "$HARNESS_DIR/$name" ]]; then
      legacy_launcher_files+=("$HARNESS_DIR/$name")
    fi
  done

  if [[ -f "$HARNESS_DIR/RunSuite.java" ]]; then
    quarantined_entrypoint_files+=("$HARNESS_DIR/RunSuite.java")
  fi
fi

runsuite_external_refs="$(java_refs_outside_harness 'org\.apache\.derbyTesting\.functionTests\.harness\.RunSuite|import[[:space:]]+org\.apache\.derbyTesting\.functionTests\.harness\.RunSuite|\bRunSuite\b')"
runtest_external_refs="$(java_refs_outside_harness 'org\.apache\.derbyTesting\.functionTests\.harness\.RunTest|import[[:space:]]+org\.apache\.derbyTesting\.functionTests\.harness\.RunTest|\bRunTest\b')"
jvm_adapter_external_refs="$(java_refs_outside_harness 'org\.apache\.derbyTesting\.functionTests\.harness\.(jdk[0-9]+|ibm[0-9]+|j9_[A-Za-z0-9_]+)|import[[:space:]]+org\.apache\.derbyTesting\.functionTests\.harness\.(jdk[0-9]+|ibm[0-9]+|j9_[A-Za-z0-9_]+)')"
gradle_refs="$(gradle_entrypoint_refs)"
shell_refs="$(shell_entrypoint_refs)"

runsuite_external_count="$(printf '%s\n' "$runsuite_external_refs" | sed '/^$/d' | count_lines)"
runtest_external_count="$(printf '%s\n' "$runtest_external_refs" | sed '/^$/d' | count_lines)"
jvm_adapter_external_count="$(printf '%s\n' "$jvm_adapter_external_refs" | sed '/^$/d' | count_lines)"
gradle_ref_count="$(printf '%s\n' "$gradle_refs" | sed '/^$/d' | count_lines)"
shell_ref_count="$(printf '%s\n' "$shell_refs" | sed '/^$/d' | count_lines)"

active_lang_suite_line=""
quarantine_symbol_line=""
if [[ -f "$TEST_BUILD_FILE" ]]; then
  active_lang_suite_line="$(grep -n "org/apache/derbyTesting/functionTests/tests/lang/_Suite.class" "$TEST_BUILD_FILE" || true)"
  quarantine_symbol_line="$(grep -n "legacyHarnessQuarantineExcludes" "$TEST_BUILD_FILE" || true)"
fi

quarantine_exclude_count=0
missing_quarantine_excludes=()
for file in "${stale_adapter_files[@]}" "${quarantined_entrypoint_files[@]}"; do
  [[ -e "$file" ]] || continue
  rel="$(relative "$file")"
  rel_under_test_src="${rel#delosdb-tests/src/test/java/}"
  if listed_as_gradle_exclude "$rel_under_test_src"; then
    quarantine_exclude_count=$((quarantine_exclude_count + 1))
  else
    missing_quarantine_excludes+=("$rel")
  fi
done

cat > "$REPORT_FILE" <<EOF_REPORT
# Legacy Derby Harness Audit

Generated by dev/legacy-derby-harness-audit.sh.

This report classifies the old Apache Derby function-test harness. DelosDB keeps the historical harness sources in the tree for reference, but the active Gradle workflow runs the inherited JUnit language suite directly. The old RunSuite process launcher and obsolete VM adapter classes are quarantined from active test-module compilation.

## Summary

| Area | Count |
|---|---:|
| Stale VM adapter sources retained for reference | ${#stale_adapter_files[@]} |
| Required VM bridge sources still compiled | ${#required_bridge_files[@]} |
| Legacy launcher/support sources still compiled for compatibility | ${#legacy_launcher_files[@]} |
| Quarantined legacy entrypoint sources | ${#quarantined_entrypoint_files[@]} |
| Quarantined sources listed in Gradle excludes | ${quarantine_exclude_count} |
| External Java references to RunSuite | ${runsuite_external_count} |
| External Java references to RunTest | ${runtest_external_count} |
| External Java references to stale VM adapters | ${jvm_adapter_external_count} |
| Gradle references to RunSuite/RunTest entrypoints | ${gradle_ref_count} |
| Shell-script references to RunSuite/RunTest entrypoints | ${shell_ref_count} |

## Active Gradle inherited-suite entrypoint

Expected DelosDB Gradle entrypoint:

    ./gradlew :delosdb-tests:runDerbyLangSuite

Expected JUnit suite include:

    org/apache/derbyTesting/functionTests/tests/lang/_Suite.class

delosdb-tests/build.gradle match:

~~~text
${active_lang_suite_line:-No active language-suite include found.}
~~~

Gradle quarantine marker:

~~~text
${quarantine_symbol_line:-No legacyHarnessQuarantineExcludes marker found.}
~~~

## Stale VM adapter sources retained for source reference

~~~text
EOF_REPORT

if [[ ${#stale_adapter_files[@]} -eq 0 ]]; then
  echo "None found." >> "$REPORT_FILE"
else
  for file in "${stale_adapter_files[@]}"; do
    relative "$file" >> "$REPORT_FILE"
    echo >> "$REPORT_FILE"
  done
fi

cat >> "$REPORT_FILE" <<EOF_REPORT
~~~

## Required VM bridge sources still compiled

~~~text
EOF_REPORT

if [[ ${#required_bridge_files[@]} -eq 0 ]]; then
  echo "None found." >> "$REPORT_FILE"
else
  for file in "${required_bridge_files[@]}"; do
    relative "$file" >> "$REPORT_FILE"
    echo >> "$REPORT_FILE"
  done
fi

cat >> "$REPORT_FILE" <<EOF_REPORT
~~~

Interpretation: jvm.java and currentjvm.java stay compiled because inherited RunTest/NetServer code can still reach the bridge reflectively if someone invokes the old runner manually. The obsolete concrete adapter classes are the stale part.

## Legacy launcher/support files still compiled for compatibility

~~~text
EOF_REPORT

if [[ ${#legacy_launcher_files[@]} -eq 0 ]]; then
  echo "None found." >> "$REPORT_FILE"
else
  for file in "${legacy_launcher_files[@]}"; do
    relative "$file" >> "$REPORT_FILE"
    echo >> "$REPORT_FILE"
  done
fi

cat >> "$REPORT_FILE" <<EOF_REPORT
~~~

Interpretation: RunTest is still referenced by inherited utility code, and RunList/NetServer are compile-time dependencies of RunTest. These files are not cleaned up in this pass.

## Quarantined legacy entrypoint sources

~~~text
EOF_REPORT

if [[ ${#quarantined_entrypoint_files[@]} -eq 0 ]]; then
  echo "None found." >> "$REPORT_FILE"
else
  for file in "${quarantined_entrypoint_files[@]}"; do
    relative "$file" >> "$REPORT_FILE"
    echo >> "$REPORT_FILE"
  done
fi

cat >> "$REPORT_FILE" <<EOF_REPORT
~~~

## Quarantine exclude coverage

~~~text
EOF_REPORT

if [[ ${#missing_quarantine_excludes[@]} -eq 0 ]]; then
  echo "All stale VM adapters and RunSuite.java are listed in legacyHarnessQuarantineExcludes." >> "$REPORT_FILE"
else
  printf '%s\n' "${missing_quarantine_excludes[@]}" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" <<EOF_REPORT
~~~

## External Java references to RunSuite

~~~text
${runsuite_external_refs:-None found.}
~~~

## External Java references to RunTest

~~~text
${runtest_external_refs:-None found.}
~~~

## External Java references to stale VM adapters

~~~text
${jvm_adapter_external_refs:-None found.}
~~~

## Gradle references to old harness entrypoints

~~~text
${gradle_refs:-None found.}
~~~

## Shell references to old harness entrypoints

~~~text
${shell_refs:-None found.}
~~~

## Quarantine status

1. RunSuite.java is retained in the source tree but excluded from active Gradle test-module compilation.
2. Obsolete concrete VM adapters such as jdk13.java, jdk110.java, ibm13.java, and j9_13.java are retained in the source tree but excluded from active Gradle test-module compilation.
3. RunTest.java, RunList.java, NetServer.java, jvm.java, and currentjvm.java remain compiled because inherited utility code still depends on that compatibility surface.
4. The next cleanup step, after repeated green Gradle runs, is to consider moving the quarantined sources under a legacy reference source tree or deleting them with a safe project-owned cleanup script.

EOF_REPORT

if [[ "$VERIFY" == true ]]; then
  failed=false

  required_files=(
    "$HARNESS_DIR/RunSuite.java"
    "$HARNESS_DIR/RunTest.java"
    "$HARNESS_DIR/RunList.java"
    "$HARNESS_DIR/NetServer.java"
    "$HARNESS_DIR/jvm.java"
    "$HARNESS_DIR/currentjvm.java"
  )

  for file in "${required_files[@]}"; do
    if [[ ! -f "$file" ]]; then
      echo "Legacy harness audit failed: required inherited harness landmark is missing: $(relative "$file")" >&2
      failed=true
    fi
  done

  if [[ -z "$active_lang_suite_line" ]]; then
    echo "Legacy harness audit failed: active Gradle language-suite include was not found in delosdb-tests/build.gradle." >&2
    failed=true
  fi

  if [[ -z "$quarantine_symbol_line" ]]; then
    echo "Legacy harness audit failed: legacyHarnessQuarantineExcludes was not found in delosdb-tests/build.gradle." >&2
    failed=true
  fi

  if [[ ${#missing_quarantine_excludes[@]} -ne 0 ]]; then
    echo "Legacy harness audit failed: some stale VM adapters or RunSuite.java are not listed in the Gradle quarantine excludes." >&2
    printf '  %s\n' "${missing_quarantine_excludes[@]}" >&2
    failed=true
  fi

  if [[ "$runsuite_external_count" != "0" ]]; then
    echo "Legacy harness audit failed: RunSuite has external Java references; inspect $REPORT_FILE before quarantine." >&2
    failed=true
  fi

  if [[ "$jvm_adapter_external_count" != "0" ]]; then
    echo "Legacy harness audit failed: stale VM adapters have external Java references; inspect $REPORT_FILE before quarantine." >&2
    failed=true
  fi

  if [[ "$gradle_ref_count" != "0" ]]; then
    echo "Legacy harness audit failed: Gradle still references RunSuite/RunTest entrypoints; inspect $REPORT_FILE before quarantine." >&2
    failed=true
  fi

  if [[ "$shell_ref_count" != "0" ]]; then
    echo "Legacy harness audit failed: shell scripts still reference RunSuite/RunTest entrypoints; inspect $REPORT_FILE before quarantine." >&2
    failed=true
  fi

  if [[ "$failed" == true ]]; then
    echo "See $REPORT_FILE" >&2
    exit 1
  fi
fi

echo "Legacy Derby harness audit written to $REPORT_FILE"
