#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/inherited-code-quality"
REPORT_FILE="$REPORT_DIR/legacy-derby-harness-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

HARNESS_DIR="$ROOT_DIR/delosdb-tests/src/test/java/org/apache/derbyTesting/functionTests/harness"
TEST_SRC="$ROOT_DIR/delosdb-tests/src/test/java"
TEST_BUILD_FILE="$ROOT_DIR/delosdb-tests/build.gradle"

relative() {
  local path="$1"
  printf '%s' "${path#${ROOT_DIR}/}"
}

count_lines() {
  wc -l | tr -d ' '
}

find_project_files() {
  find "$ROOT_DIR" \
    -path "$ROOT_DIR/.git" -prune -o \
    -path "$ROOT_DIR/.gradle" -prune -o \
    -path "$ROOT_DIR/.idea" -prune -o \
    -path "$ROOT_DIR/build" -prune -o \
    -path '*/build' -prune -o \
    "$@"
}

java_refs_outside_harness() {
  local pattern="$1"
  if [[ ! -d "$TEST_SRC" ]]; then
    return 0
  fi
  find "$TEST_SRC" \
    -path "$HARNESS_DIR" -prune -o \
    -name '*.java' -type f -print0 \
    | xargs -0 grep -n -E "$pattern" 2>/dev/null \
    | sed "s#${ROOT_DIR}/##" \
    | grep -Ev '^[^:]+:[0-9]+:[[:space:]]*(//|/\*|\*)' \
    || true
}

gradle_entrypoint_refs() {
  find_project_files \( -name '*.gradle' -o -name 'settings.gradle' -o -name 'gradle.properties' \) -type f -print0 \
    | xargs -0 grep -n -E 'org\.apache\.derbyTesting\.functionTests\.harness\.(RunSuite|RunTest)|mainClass[[:space:]]*=.*RunSuite|mainClass[[:space:]]*=.*RunTest|RunSuite\.class|RunTest\.class' 2>/dev/null \
    | sed "s#${ROOT_DIR}/##" \
    || true
}

shell_entrypoint_refs() {
  find_project_files \( -name '*.sh' -o -name '*.bash' \) -type f -print0 \
    | xargs -0 grep -n -E 'org\.apache\.derbyTesting\.functionTests\.harness\.(RunSuite|RunTest)|RunSuite\.class|RunTest\.class' 2>/dev/null \
    | sed "s#${ROOT_DIR}/##" \
    | grep -Ev 'dev/legacy-derby-harness-audit\.sh' \
    || true
}

legacy_jvm_files=()
legacy_launcher_files=()
if [[ -d "$HARNESS_DIR" ]]; then
  while IFS= read -r -d '' file; do
    legacy_jvm_files+=("$file")
  done < <(find "$HARNESS_DIR" -maxdepth 1 -type f \
    \( -name 'jdk*.java' -o -name 'ibm*.java' -o -name 'j9*.java' -o -name 'currentjvm.java' -o -name 'jvm.java' \) \
    -print0 | sort -z)

  while IFS= read -r -d '' file; do
    legacy_launcher_files+=("$file")
  done < <(find "$HARNESS_DIR" -maxdepth 1 -type f \
    \( -name 'RunSuite.java' -o -name 'RunTest.java' -o -name 'RunList.java' -o -name 'NetServer.java' \) \
    -print0 | sort -z)
fi

runsuite_external_refs="$(java_refs_outside_harness 'org\.apache\.derbyTesting\.functionTests\.harness\.RunSuite|import[[:space:]]+org\.apache\.derbyTesting\.functionTests\.harness\.RunSuite|\bRunSuite\b')"
runtest_external_refs="$(java_refs_outside_harness 'org\.apache\.derbyTesting\.functionTests\.harness\.RunTest|import[[:space:]]+org\.apache\.derbyTesting\.functionTests\.harness\.RunTest|\bRunTest\b')"
jvm_adapter_external_refs="$(java_refs_outside_harness 'org\.apache\.derbyTesting\.functionTests\.harness\.(jdk[0-9]+|ibm[0-9]+|j9_[A-Za-z0-9_]+|currentjvm)|import[[:space:]]+org\.apache\.derbyTesting\.functionTests\.harness\.(jdk[0-9]+|ibm[0-9]+|j9_[A-Za-z0-9_]+|currentjvm)')"
gradle_refs="$(gradle_entrypoint_refs)"
shell_refs="$(shell_entrypoint_refs)"

runsuite_external_count="$(printf '%s\n' "$runsuite_external_refs" | sed '/^$/d' | count_lines)"
runtest_external_count="$(printf '%s\n' "$runtest_external_refs" | sed '/^$/d' | count_lines)"
jvm_adapter_external_count="$(printf '%s\n' "$jvm_adapter_external_refs" | sed '/^$/d' | count_lines)"
gradle_ref_count="$(printf '%s\n' "$gradle_refs" | sed '/^$/d' | count_lines)"
shell_ref_count="$(printf '%s\n' "$shell_refs" | sed '/^$/d' | count_lines)"

active_lang_suite_line=""
if [[ -f "$TEST_BUILD_FILE" ]]; then
  active_lang_suite_line="$(grep -n "org/apache/derbyTesting/functionTests/tests/lang/_Suite.class" "$TEST_BUILD_FILE" || true)"
fi

cat > "$REPORT_FILE" <<EOF_REPORT
# Legacy Derby Harness Audit

Generated by dev/legacy-derby-harness-audit.sh.

This report classifies the old Apache Derby function-test harness before any removal or source-set isolation. The DelosDB Gradle workflow runs the inherited JUnit language suite directly; it does not use the historical Ant-era RunSuite launcher path.

## Summary

| Area | Count |
|---|---:|
| Legacy JVM adapter/support files in harness | ${#legacy_jvm_files[@]} |
| Legacy harness launcher files | ${#legacy_launcher_files[@]} |
| External Java references to RunSuite | ${runsuite_external_count} |
| External Java references to RunTest | ${runtest_external_count} |
| External Java references to legacy JVM adapters | ${jvm_adapter_external_count} |
| Gradle references to RunSuite/RunTest entrypoints | ${gradle_ref_count} |
| Shell-script references to RunSuite/RunTest entrypoints | ${shell_ref_count} |

## Active Gradle inherited-suite entrypoint

Expected DelosDB Gradle entrypoint:

    ./gradlew :delosdb-tests:runDerbyLangSuite

Expected JUnit suite include:

    org/apache/derbyTesting/functionTests/tests/lang/_Suite.class

delosdb-tests/build.gradle match:

~~~text
${active_lang_suite_line:-No active language-suite include found.}
~~~

## Legacy JVM adapter/support files

~~~text
EOF_REPORT

if [[ ${#legacy_jvm_files[@]} -eq 0 ]]; then
  echo "None found." >> "$REPORT_FILE"
else
  for file in "${legacy_jvm_files[@]}"; do
    relative "$file" >> "$REPORT_FILE"
    echo >> "$REPORT_FILE"
  done
fi

cat >> "$REPORT_FILE" <<EOF_REPORT
~~~

## Legacy harness launcher files

~~~text
EOF_REPORT

if [[ ${#legacy_launcher_files[@]} -eq 0 ]]; then
  echo "None found." >> "$REPORT_FILE"
else
  for file in "${legacy_launcher_files[@]}"; do
    relative "$file" >> "$REPORT_FILE"
    echo >> "$REPORT_FILE"
  done
fi

cat >> "$REPORT_FILE" <<EOF_REPORT
~~~

## External Java references to RunSuite

~~~text
${runsuite_external_refs:-None found.}
~~~

## External Java references to RunTest

~~~text
${runtest_external_refs:-None found.}
~~~

Interpretation: RunTest is still referenced by inherited utility code, so it should not be deleted yet. The safer first cleanup target is the old JVM adapter layer and the unused RunSuite entrypoint path, not shared utility methods exposed by RunTest.

## External Java references to legacy JVM adapters

~~~text
${jvm_adapter_external_refs:-None found.}
~~~

## Gradle references to old harness entrypoints

~~~text
${gradle_refs:-None found.}
~~~

## Shell references to old harness entrypoints

~~~text
${shell_refs:-None found.}
~~~

## Quarantine recommendation

1. Keep RunTest for now because inherited utility code still references it.
2. Treat RunSuite, RunList, and the JVM adapter classes as legacy harness surface, not active DelosDB test infrastructure.
3. Do not delete anything until the Gradle language-suite compile/run gates pass with a source-set quarantine.
4. The next safe implementation step is to exclude only the proven legacy launcher/adapters from the active Gradle test compile, while leaving the files in the tree for source reference.

EOF_REPORT

if [[ "$VERIFY" == true ]]; then
  failed=false

  required_files=(
    "$HARNESS_DIR/RunSuite.java"
    "$HARNESS_DIR/RunTest.java"
    "$HARNESS_DIR/RunList.java"
    "$HARNESS_DIR/jvm.java"
  )

  for file in "${required_files[@]}"; do
    if [[ ! -f "$file" ]]; then
      echo "Legacy harness audit failed: required inherited harness landmark is missing: $(relative "$file")" >&2
      failed=true
    fi
  done

  if [[ -z "$active_lang_suite_line" ]]; then
    echo "Legacy harness audit failed: active Gradle language-suite include was not found in delosdb-tests/build.gradle." >&2
    failed=true
  fi

  if [[ "$runsuite_external_count" != "0" ]]; then
    echo "Legacy harness audit failed: RunSuite has external Java references; inspect $REPORT_FILE before quarantine." >&2
    failed=true
  fi

  if [[ "$jvm_adapter_external_count" != "0" ]]; then
    echo "Legacy harness audit failed: legacy JVM adapters have external Java references; inspect $REPORT_FILE before quarantine." >&2
    failed=true
  fi

  if [[ "$gradle_ref_count" != "0" ]]; then
    echo "Legacy harness audit failed: Gradle still references RunSuite/RunTest entrypoints; inspect $REPORT_FILE before quarantine." >&2
    failed=true
  fi

  if [[ "$shell_ref_count" != "0" ]]; then
    echo "Legacy harness audit failed: shell scripts still reference RunSuite/RunTest entrypoints; inspect $REPORT_FILE before quarantine." >&2
    failed=true
  fi

  if [[ "$failed" == true ]]; then
    echo "See $REPORT_FILE" >&2
    exit 1
  fi
fi

echo "Legacy Derby harness audit written to $REPORT_FILE"
