#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/modernization"
REPORT_FILE="$REPORT_DIR/modernization-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

PRODUCTION_ROOTS=(
  "$ROOT_DIR/delosdb-client/src/main/java"
  "$ROOT_DIR/delosdb-commons/src/main/java"
  "$ROOT_DIR/delosdb-engine/src/main/java"
  "$ROOT_DIR/delosdb-optionaltools/src/main/java"
  "$ROOT_DIR/delosdb-runner/src/main/java"
  "$ROOT_DIR/delosdb-server/src/main/java"
  "$ROOT_DIR/java/org.apache.derby.shared"
  "$ROOT_DIR/delosdb-tools/src/main/java"
)

ALL_TREE_ROOTS=(
  "$ROOT_DIR/java"
  "$ROOT_DIR/delosdb-tests/src/test/java"
  "$ROOT_DIR/delosdb-pptesting/src/test/java"
  "$ROOT_DIR/delosdb-demos/src/main/demo"
  "$ROOT_DIR/delosdb-storeless/src/main/java"
  "$ROOT_DIR/delosdb-buildtools/src/main/java"
)

count_matches() {
  local pattern="$1"
  {
    grep -R --include='*.java' -E "$pattern" "${PRODUCTION_ROOTS[@]}" 2>/dev/null \
      | grep -Ev '^[^:]+:[[:space:]]*(//|/\*|\*)|^[[:space:]]*(//|/\*|\*)' \
      || true
  } | wc -l | tr -d ' '
}

write_matches() {
  local title="$1"
  local pattern="$2"
  {
    echo
    echo "## $title"
    echo
    grep -R --include='*.java' -n -E "$pattern" "${PRODUCTION_ROOTS[@]}" 2>/dev/null \
      | sed "s#${ROOT_DIR}/##" \
      | grep -Ev '^[^:]+:[0-9]+:[[:space:]]*(//|/\*|\*)' \
      | head -200 \
      || true
  } >> "$REPORT_FILE"
}


write_filtered_matches() {
  local title="$1"
  local pattern="$2"
  local path_filter="$3"
  local filter_mode="$4"
  local matches

  {
    echo
    echo "## $title"
    echo

    matches=$(grep -R --include='*.java' -n -E "$pattern" "${PRODUCTION_ROOTS[@]}" 2>/dev/null \
      | sed "s#${ROOT_DIR}/##" \
      | grep -Ev '^[^:]+:[0-9]+:[[:space:]]*(//|/\*|\*)' \
      || true)

    if [[ -z "$matches" ]]; then
      return
    fi

    if [[ "$filter_mode" == "include" ]]; then
      printf '%s\n' "$matches" | grep -E "$path_filter" | head -200 || true
    else
      printf '%s\n' "$matches" | grep -Ev "$path_filter" | head -200 || true
    fi
  } >> "$REPORT_FILE"
}

count_all_matches() {
  local pattern="$1"
  {
    grep -R --include='*.java' -E "$pattern" "${ALL_TREE_ROOTS[@]}" 2>/dev/null \
      | grep -Ev '^[^:]+:[[:space:]]*(//|/\*|\*)|^[[:space:]]*(//|/\*|\*)' \
      || true
  } | wc -l | tr -d ' '
}


count_filtered_matches() {
  local pattern="$1"
  local path_filter="$2"
  local filter_mode="$3"
  local matches
  local filtered

  matches=$(grep -R --include='*.java' -n -E "$pattern" "${PRODUCTION_ROOTS[@]}" 2>/dev/null     | sed "s#${ROOT_DIR}/##"     | grep -Ev '^[^:]+:[0-9]+:[[:space:]]*(//|/\*|\*)'     || true)

  if [[ -z "$matches" ]]; then
    echo 0
    return
  fi

  if [[ "$filter_mode" == "include" ]]; then
    filtered=$(printf '%s
' "$matches" | grep -E "$path_filter" || true)
  else
    filtered=$(printf '%s
' "$matches" | grep -Ev "$path_filter" || true)
  fi

  if [[ -z "$filtered" ]]; then
    echo 0
  else
    printf '%s
' "$filtered" | wc -l | tr -d ' '
  fi
}

production_finalizers="$(count_matches 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\(')"
production_get_security_manager="$(count_matches 'System\.getSecurityManager[[:space:]]*\(')"
production_do_privileged="$(count_matches 'AccessController\.doPrivileged|doPrivileged[[:space:]]*\(')"
production_access_controller="$(count_matches 'java\.security\.AccessController|AccessController\.')"

# Match legacy java.util collection usage precisely enough to avoid counting
# project-specific class names such as QueryTreeNodeVector or DiskHashtable.
VECTOR_USAGE_PATTERN='new[[:space:]]+(java\.util\.)?Vector[[:space:]]*(<|\()|(^|[^[:alnum:]_])Vector[[:space:]]*<'
HASHTABLE_USAGE_PATTERN='new[[:space:]]+(java\.util\.)?Hashtable[[:space:]]*(<|\()|(^|[^[:alnum:]_])Hashtable[[:space:]]*<'

# The legacy collection modernization pass has eliminated all production
# Vector usages and all modernizable production Hashtable usages. The only
# remaining Hashtable matches are intentionally retained for stored-format and
# JNDI ObjectFactory contracts. Treat every other production Hashtable match as
# a regression.
ALLOWED_HASHTABLE_PATH_PATTERN='iapi/services/io/FormatableHashtable|org/apache/derby/jdbc/EmbeddedDataSource|org/apache/derby/jdbc/ReferenceableDataSource'

production_vector_usage="$(count_matches "$VECTOR_USAGE_PATTERN")"
production_hashtable_usage="$(count_matches "$HASHTABLE_USAGE_PATTERN")"
allowed_hashtable_usage="$(count_filtered_matches "$HASHTABLE_USAGE_PATTERN" "$ALLOWED_HASHTABLE_PATH_PATTERN" include)"
unexpected_hashtable_usage="$(count_filtered_matches "$HASHTABLE_USAGE_PATTERN" "$ALLOWED_HASHTABLE_PATH_PATTERN" exclude)"



cat > "$REPORT_FILE" <<EOF_REPORT
# DelosDB Modernization Audit

Generated by \`dev/modernization-audit.sh\`.

This report focuses on production modules. Historical demo material and the inherited test tree are intentionally excluded from the primary counts so the audit reflects active runtime code.

| Area | Production match count |
|---|---:|
| Object finalizer overrides | ${production_finalizers} |
| System.getSecurityManager calls | ${production_get_security_manager} |
| AccessController references | ${production_access_controller} |
| doPrivileged calls | ${production_do_privileged} |
| Vector usage | ${production_vector_usage} |
| Hashtable usage | ${production_hashtable_usage} |
| Allowed contract/stored-format Hashtable usage | ${allowed_hashtable_usage} |
| Unexpected Hashtable usage | ${unexpected_hashtable_usage} |

Secondary all-tree counts, including inherited tests/demo/history:

| Area | All-tree match count |
|---|---:|
| Object finalizer overrides | $(count_all_matches 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\(') |
| SecurityManager references | $(count_all_matches 'SecurityManager|System\.getSecurityManager') |
| AccessController references | $(count_all_matches 'java\.security\.AccessController|AccessController\.') |
| doPrivileged calls | $(count_all_matches 'doPrivileged[[:space:]]*\\(') |

EOF_REPORT

write_matches "Production Object finalizer overrides" 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\('
write_matches "Production System.getSecurityManager calls" 'System\.getSecurityManager[[:space:]]*\('
write_matches "Production AccessController references" 'java\.security\.AccessController|AccessController\.'
write_matches "Production doPrivileged calls" 'AccessController\.doPrivileged|doPrivileged[[:space:]]*\('
write_matches "Production Vector usage" "$VECTOR_USAGE_PATTERN"
write_matches "Production Hashtable usage" "$HASHTABLE_USAGE_PATTERN"
write_filtered_matches "Allowed contract/stored-format Hashtable usage" "$HASHTABLE_USAGE_PATTERN" "$ALLOWED_HASHTABLE_PATH_PATTERN" include
write_filtered_matches "Remaining candidate Vector usage" "$VECTOR_USAGE_PATTERN" '^$' exclude
write_filtered_matches "Remaining candidate Hashtable usage" "$HASHTABLE_USAGE_PATTERN" "$ALLOWED_HASHTABLE_PATH_PATTERN" exclude

if [[ "$VERIFY" == true ]]; then
  failed=false

  if [[ "$production_finalizers" != "0" ]]; then
    echo "Modernization audit failed: production Object finalizer overrides remain." >&2
    failed=true
  fi

  if [[ "$production_get_security_manager" != "0" ]]; then
    echo "Modernization audit failed: production System.getSecurityManager calls remain." >&2
    failed=true
  fi

  if [[ "$production_do_privileged" != "0" ]]; then
    echo "Modernization audit failed: production doPrivileged calls remain." >&2
    failed=true
  fi

  if [[ "$production_access_controller" != "0" ]]; then
    echo "Modernization audit failed: production AccessController references remain." >&2
    failed=true
  fi

  if [[ "$production_vector_usage" != "0" ]]; then
    echo "Modernization audit failed: production Vector usages remain." >&2
    failed=true
  fi

  if [[ "$unexpected_hashtable_usage" != "0" ]]; then
    echo "Modernization audit failed: unexpected production Hashtable usages remain." >&2
    failed=true
  fi

  if [[ "$failed" == true ]]; then
    echo "See $REPORT_FILE" >&2
    exit 1
  fi
fi

echo "Modernization audit written to $REPORT_FILE"
