#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/modernization"
REPORT_FILE="$REPORT_DIR/modernization-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

PRODUCTION_ROOTS=(
  "$ROOT_DIR/java/org.apache.derby.client"
  "$ROOT_DIR/java/org.apache.derby.commons"
  "$ROOT_DIR/java/org.apache.derby.engine"
  "$ROOT_DIR/java/org.apache.derby.optionaltools"
  "$ROOT_DIR/java/org.apache.derby.runner"
  "$ROOT_DIR/java/org.apache.derby.server"
  "$ROOT_DIR/java/org.apache.derby.shared"
  "$ROOT_DIR/java/org.apache.derby.tools"
)

count_matches() {
  local pattern="$1"
  {
    grep -R --include='*.java' -E "$pattern" "${PRODUCTION_ROOTS[@]}" 2>/dev/null \
      | grep -Ev '^[^:]+:[[:space:]]*(//|/\*|\*)|^[[:space:]]*(//|/\*|\*)' \
      || true
  } | wc -l | tr -d ' '
}

write_matches() {
  local title="$1"
  local pattern="$2"
  {
    echo
    echo "## $title"
    echo
    grep -R --include='*.java' -n -E "$pattern" "${PRODUCTION_ROOTS[@]}" 2>/dev/null \
      | sed "s#${ROOT_DIR}/##" \
      | grep -Ev '^[^:]+:[0-9]+:[[:space:]]*(//|/\*|\*)' \
      | head -200 \
      || true
  } >> "$REPORT_FILE"
}

count_all_matches() {
  local pattern="$1"
  {
    grep -R --include='*.java' -E "$pattern" "$ROOT_DIR/java" 2>/dev/null \
      | grep -Ev '^[^:]+:[[:space:]]*(//|/\*|\*)|^[[:space:]]*(//|/\*|\*)' \
      || true
  } | wc -l | tr -d ' '
}

production_finalizers="$(count_matches 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\(')"
production_get_security_manager="$(count_matches 'System\.getSecurityManager[[:space:]]*\(')"
production_do_privileged="$(count_matches 'AccessController\.doPrivileged|doPrivileged[[:space:]]*\(')"
production_access_controller="$(count_matches 'java\.security\.AccessController|AccessController\.')"

# Match legacy java.util collection usage precisely enough to avoid counting
# project-specific class names such as QueryTreeNodeVector or DiskHashtable.
VECTOR_USAGE_PATTERN='new[[:space:]]+(java\.util\.)?Vector[[:space:]]*(<|\()|(^|[^[:alnum:]_])Vector[[:space:]]*<'
HASHTABLE_USAGE_PATTERN='new[[:space:]]+(java\.util\.)?Hashtable[[:space:]]*(<|\()|(^|[^[:alnum:]_])Hashtable[[:space:]]*<'


cat > "$REPORT_FILE" <<EOF_REPORT
# DelosDB Modernization Audit

Generated by \`dev/modernization-audit.sh\`.

This report focuses on production modules. Historical demo material and the inherited test tree are intentionally excluded from the primary counts so the audit reflects active runtime code.

| Area | Production match count |
|---|---:|
| Object finalizer overrides | ${production_finalizers} |
| System.getSecurityManager calls | ${production_get_security_manager} |
| AccessController references | ${production_access_controller} |
| doPrivileged calls | ${production_do_privileged} |
| Vector usage | $(count_matches "$VECTOR_USAGE_PATTERN") |
| Hashtable usage | $(count_matches "$HASHTABLE_USAGE_PATTERN") |

Secondary all-tree counts, including inherited tests/demo/history:

| Area | All-tree match count |
|---|---:|
| Object finalizer overrides | $(count_all_matches 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\(') |
| SecurityManager references | $(count_all_matches 'SecurityManager|System\.getSecurityManager') |
| AccessController references | $(count_all_matches 'java\.security\.AccessController|AccessController\.') |
| doPrivileged calls | $(count_all_matches 'doPrivileged[[:space:]]*\\(') |

EOF_REPORT

write_matches "Production Object finalizer overrides" 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\('
write_matches "Production System.getSecurityManager calls" 'System\.getSecurityManager[[:space:]]*\('
write_matches "Production AccessController references" 'java\.security\.AccessController|AccessController\.'
write_matches "Production doPrivileged calls" 'AccessController\.doPrivileged|doPrivileged[[:space:]]*\('
write_matches "Production Vector usage" "$VECTOR_USAGE_PATTERN" 
write_matches "Production Hashtable usage" "$HASHTABLE_USAGE_PATTERN" 

if [[ "$VERIFY" == true ]]; then
  failed=false

  if [[ "$production_finalizers" != "0" ]]; then
    echo "Modernization audit failed: production Object finalizer overrides remain." >&2
    failed=true
  fi

  if [[ "$production_get_security_manager" != "0" ]]; then
    echo "Modernization audit failed: production System.getSecurityManager calls remain." >&2
    failed=true
  fi

  if [[ "$production_do_privileged" != "0" ]]; then
    echo "Modernization audit failed: production doPrivileged calls remain." >&2
    failed=true
  fi

  if [[ "$failed" == true ]]; then
    echo "See $REPORT_FILE" >&2
    exit 1
  fi
fi

echo "Modernization audit written to $REPORT_FILE"
