#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/modernization"
REPORT_FILE="$REPORT_DIR/modernization-audit.md"

mkdir -p "$REPORT_DIR"

count_matches() {
  local pattern="$1"
  grep -R --include='*.java' -E "$pattern" "$ROOT_DIR/java" 2>/dev/null | wc -l | tr -d ' '
}

write_matches() {
  local title="$1"
  local pattern="$2"
  {
    echo
    echo "## $title"
    echo
    grep -R --include='*.java' -n -E "$pattern" "$ROOT_DIR/java" 2>/dev/null \
      | sed "s#${ROOT_DIR}/##" \
      | head -200 \
      || true
  } >> "$REPORT_FILE"
}

cat > "$REPORT_FILE" <<EOF_REPORT
# DelosDB Modernization Audit

Generated by \`dev/modernization-audit.sh\`.

| Area | Match count |
|---|---:|
| Finalizers | $(count_matches 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\(') |
| SecurityManager references | $(count_matches 'SecurityManager|System\.getSecurityManager') |
| AccessController references | $(count_matches 'java\.security\.AccessController|AccessController\.') |
| doPrivileged references | $(count_matches 'doPrivileged[[:space:]]*\(') |
| Vector usage | $(count_matches 'new[[:space:]]+Vector|Vector[[:space:]]*<') |
| Hashtable usage | $(count_matches 'new[[:space:]]+Hashtable|Hashtable[[:space:]]*<') |

EOF_REPORT

write_matches "Finalizers" 'protected[[:space:]]+void[[:space:]]+finalize[[:space:]]*\('
write_matches "SecurityManager references" 'SecurityManager|System\.getSecurityManager'
write_matches "AccessController references" 'java\.security\.AccessController|AccessController\.'
write_matches "doPrivileged references" 'doPrivileged[[:space:]]*\('
write_matches "Vector usage" 'new[[:space:]]+Vector|Vector[[:space:]]*<' 
write_matches "Hashtable usage" 'new[[:space:]]+Hashtable|Hashtable[[:space:]]*<' 

echo "Modernization audit written to $REPORT_FILE"
