#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/sort-memory-observability"
REPORT_FILE="$REPORT_DIR/sort-memory-observability-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

factory="delosdb-engine/src/main/java/org/apache/derby/impl/store/access/sort/ExternalSortFactory.java"
probe="delosdb-buildtools/src/main/java/org/apache/derby/impl/store/access/sort/SortMemoryPolicyProbe.java"

require_file() {
  local path="$1"
  if [[ ! -f "$ROOT_DIR/$path" ]]; then
    echo "Missing required file: $path" >&2
    exit 1
  fi
}

count_literal() {
  local literal="$1"
  local path="$2"
  grep -F "$literal" "$ROOT_DIR/$path" 2>/dev/null | wc -l | tr -d ' '
}

match_lines() {
  local pattern="$1"
  local path="$2"
  grep -n -E "$pattern" "$ROOT_DIR/$path" 2>/dev/null | sed "s#^#$path:#" || true
}

require_file "$factory"
require_file "$probe"

estimate_method_count="$(count_literal 'estimateSortBufferSizing(' "$factory")"
probe_call_count="$(count_literal 'estimateSortBufferSizing(' "$probe")"
default_mem_use_lines="$(match_lines 'LEGACY_DEFAULT_MEM_USE|MAX_AUTOMATIC_MEM_USE|AUTOMATIC_MEM_USE_HEAP_DIVISOR|DEFAULT_SORTBUFFERMAX|MINIMUM_SORTBUFFERMAX|SORT_ROW_OVERHEAD' "$factory")"
policy_lines="$(match_lines 'estimated-row-size-jvm-aware|default-row-count|user-property|slushAdjusted|effectiveEstimatedRowSize|automaticMemoryUse|defaultMemoryUse|SortTuning' "$factory")"
probe_lines="$(match_lines 'unknown-row-size|estimated-row-size-legacy-floor|estimated-row-size-jvm-budget|slush-adjusted|minimum-clamped|user-property|defaultMemoryUse\.floor|defaultMemoryUse\.scaled|defaultMemoryUse\.cap|legacyDefaultMemUseBytes|maxAutomaticMemUseBytes|runtimeDefaultMemUseBytes' "$probe")"

{
  echo '# DelosDB Sort Memory Policy Audit'
  echo
  echo 'Generated by `dev/sort-memory-observability-audit.sh`.'
  echo
  echo 'This report documents the DelosDB Java 21 tuning step for inherited Apache'
  echo 'Derby external-sort buffer sizing. The policy keeps Derby row-count based'
  echo 'sort buffers and preserves `derby.storage.sortBufferMax` as a hard override,'
  echo 'but no longer fixes the automatic estimated-row-size memory target at exactly'
  echo '1 MiB. Instead it uses a conservative JVM-aware budget: floor 1 MiB, cap 16'
  echo 'MiB, and otherwise roughly 1/256 of the maximum heap.'
  echo
  echo '## Summary'
  echo
  echo '| Landmark | Value |'
  echo '|---|---:|'
  echo "| External sort factory found | 1 |"
  echo "| Sort memory policy probe found | 1 |"
  echo "| Factory estimateSortBufferSizing references | ${estimate_method_count} |"
  echo "| Probe estimateSortBufferSizing references | ${probe_call_count} |"
  echo
  echo '## Policy constants'
  echo
  echo '```text'
  printf '%s\n' "$default_mem_use_lines"
  echo '```'
  echo
  echo '## Observable sizing path landmarks'
  echo
  echo '```text'
  printf '%s\n' "$policy_lines"
  echo '```'
  echo
  echo '## Probe cases'
  echo
  echo '```text'
  printf '%s\n' "$probe_lines"
  echo '```'
  echo
  echo '## Compatibility note'
  echo
  echo 'This change is performance-oriented, not semantic. Unknown row-size cases still'
  echo 'use the configured/default row-count value. User-specified'
  echo '`derby.storage.sortBufferMax` still wins. The tuning only affects the automatic'
  echo 'row-count derived from estimated row size when the user has not supplied a'
  echo 'sort-buffer row-count override.'
} > "$REPORT_FILE"

if $VERIFY; then
  grep -q 'LEGACY_DEFAULT_MEM_USE = 1024\*1024' "$ROOT_DIR/$factory"
  grep -q 'MAX_AUTOMATIC_MEM_USE = 16\*1024\*1024' "$ROOT_DIR/$factory"
  grep -q 'AUTOMATIC_MEM_USE_HEAP_DIVISOR = 256' "$ROOT_DIR/$factory"
  grep -q 'static int defaultMemoryUse' "$ROOT_DIR/$factory"
  grep -q 'estimated-row-size-jvm-aware' "$ROOT_DIR/$factory"
  grep -q 'automaticMemoryUse' "$ROOT_DIR/$factory"
  grep -q 'SortMemoryPolicyProbe' "$ROOT_DIR/$probe"
  grep -q 'estimated-row-size-jvm-budget' "$ROOT_DIR/$probe"
  grep -q 'defaultMemoryUse.cap' "$ROOT_DIR/$probe"
fi

echo "Sort memory policy audit written to $REPORT_FILE"
