#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/sort-memory-observability"
REPORT_FILE="$REPORT_DIR/sort-memory-observability-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

factory="delosdb-engine/src/main/java/org/apache/derby/impl/store/access/sort/ExternalSortFactory.java"
probe="delosdb-buildtools/src/main/java/org/apache/derby/impl/store/access/sort/SortMemoryPolicyProbe.java"

require_file() {
  local path="$1"
  if [[ ! -f "$ROOT_DIR/$path" ]]; then
    echo "Missing required file: $path" >&2
    exit 1
  fi
}

count_literal() {
  local literal="$1"
  local path="$2"
  grep -F "$literal" "$ROOT_DIR/$path" 2>/dev/null | wc -l | tr -d ' '
}

match_lines() {
  local pattern="$1"
  local path="$2"
  grep -n -E "$pattern" "$ROOT_DIR/$path" 2>/dev/null | sed "s#^#$path:#" || true
}

require_file "$factory"
require_file "$probe"

estimate_method_count="$(count_literal 'estimateSortBufferSizing(' "$factory")"
probe_call_count="$(count_literal 'estimateSortBufferSizing(' "$probe")"
default_mem_use_lines="$(match_lines 'DEFAULT_MEM_USE|DEFAULT_SORTBUFFERMAX|MINIMUM_SORTBUFFERMAX|SORT_ROW_OVERHEAD' "$factory")"
policy_lines="$(match_lines 'estimated-row-size|default-row-count|user-property|slushAdjusted|effectiveEstimatedRowSize|SortTuning' "$factory")"
probe_lines="$(match_lines 'unknown-row-size|estimated-row-size|slush-adjusted|minimum-clamped|user-property|defaultMemUseBytes' "$probe")"

{
  echo '# DelosDB Sort Memory Observability Audit'
  echo
  echo 'Generated by `dev/sort-memory-observability-audit.sh`.'
  echo
  echo 'This report documents the inherited Apache Derby external sort buffer sizing'
  echo 'policy before DelosDB changes the policy for JVM 21. The current overlay keeps'
  echo 'the policy unchanged and makes the calculation observable and probeable.'
  echo
  echo '## Summary'
  echo
  echo '| Landmark | Value |'
  echo '|---|---:|'
  echo "| External sort factory found | 1 |"
  echo "| Sort memory policy probe found | 1 |"
  echo "| Factory estimateSortBufferSizing references | ${estimate_method_count} |"
  echo "| Probe estimateSortBufferSizing references | ${probe_call_count} |"
  echo
  echo '## Fixed inherited policy landmarks'
  echo
  echo '```text'
  printf '%s\n' "$default_mem_use_lines"
  echo '```'
  echo
  echo '## Observable sizing path landmarks'
  echo
  echo '```text'
  printf '%s\n' "$policy_lines"
  echo '```'
  echo
  echo '## Probe cases'
  echo
  echo '```text'
  printf '%s\n' "$probe_lines"
  echo '```'
  echo
  echo '## Compatibility note'
  echo
  echo "The current policy still uses Derby's inherited row-count buffer limit and the"
  echo 'approximately 1 MiB memory target when estimated row size is available. This is'
  echo 'an observability step only. Future JVM 21 tuning should be benchmarked with'
  echo 'ORDER BY, DISTINCT, GROUP BY, and spill-to-disk cases before changing defaults.'
} > "$REPORT_FILE"

if $VERIFY; then
  grep -q 'DEFAULT_MEM_USE = 1024\*1024' "$ROOT_DIR/$factory"
  grep -q 'static SortBufferSizing estimateSortBufferSizing' "$ROOT_DIR/$factory"
  grep -q 'effectiveEstimatedRowSize' "$ROOT_DIR/$factory"
  grep -q 'sizingPolicy' "$ROOT_DIR/$factory"
  grep -q 'slushAdjusted' "$ROOT_DIR/$factory"
  grep -q 'SortMemoryPolicyProbe' "$ROOT_DIR/$probe"
  grep -q 'minimum-clamped' "$ROOT_DIR/$probe"
fi

echo "Sort memory observability audit written to $REPORT_FILE"
