#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/build/reports/xml-hardening"
REPORT_FILE="$REPORT_DIR/xml-hardening-audit.md"
VERIFY=false

if [[ "${1:-}" == "--verify" ]]; then
  VERIFY=true
fi

mkdir -p "$REPORT_DIR"

PRODUCTION_ROOTS=(
  "$ROOT_DIR/delosdb-client/src/main/java"
  "$ROOT_DIR/delosdb-commons/src/main/java"
  "$ROOT_DIR/delosdb-engine/src/main/java"
  "$ROOT_DIR/delosdb-optionaltools/src/main/java"
  "$ROOT_DIR/delosdb-runner/src/main/java"
  "$ROOT_DIR/delosdb-server/src/main/java"
  "$ROOT_DIR/delosdb-tools/src/main/java"
)

existing_roots=()
for root in "${PRODUCTION_ROOTS[@]}"; do
  [[ -d "$root" ]] && existing_roots+=("$root")
done

count_matches() {
  local pattern="$1"
  shift
  if [[ "$#" -eq 0 ]]; then
    echo 0
    return
  fi
  {
    grep -R --include='*.java' -E "$pattern" "$@" 2>/dev/null \
      | grep -Ev '^[^:]+:[[:space:]]*(//|/\*|\*)|^[[:space:]]*(//|/\*|\*)' \
      || true
  } | wc -l | tr -d ' '
}

write_matches() {
  local title="$1"
  local pattern="$2"
  shift 2
  {
    echo
    echo "## $title"
    echo
    if [[ "$#" -eq 0 ]]; then
      echo "No source roots found."
      return
    fi
    grep -R --include='*.java' -n -E "$pattern" "$@" 2>/dev/null \
      | sed "s#${ROOT_DIR}/##" \
      | grep -Ev '^[^:]+:[0-9]+:[[:space:]]*(//|/\*|\*)' \
      | head -200 \
      || true
  } >> "$REPORT_FILE"
}

secure_factory_file="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/iapi/xml/SecureXmlFactory.java"
sql_xml_util_file="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/iapi/types/SqlXmlUtil.java"
xml_vti_file="$ROOT_DIR/delosdb-engine/src/main/java/org/apache/derby/vti/XmlVTI.java"
probe_file="$ROOT_DIR/delosdb-buildtools/src/main/java/org/apache/derbyBuild/SecureXmlFactoryProbe.java"

xml_factory_usage="$(count_matches 'DocumentBuilderFactory|SAXParserFactory|XMLInputFactory|TransformerFactory' "${existing_roots[@]}")"
direct_document_builder_new_instance="$(count_matches 'DocumentBuilderFactory[.]newInstance[[:space:]]*\(' "${existing_roots[@]}")"
direct_transformer_new_instance="$(count_matches 'TransformerFactory[.]newInstance[[:space:]]*\(' "${existing_roots[@]}")"
secure_factory_usage="$(count_matches 'SecureXmlFactory[.]new(DocumentBuilderFactory|TransformerFactory)' "${existing_roots[@]}")"

cat > "$REPORT_FILE" <<EOF_REPORT
# XML Hardening Audit

Generated by \`dev/xml-hardening-audit.sh\`.

This report tracks the guarded Java 21 XML factory hardening pass. The current
change centralizes parser/transformer hardening and applies it to the SQL/XML
runtime parser and the XML VTI parser before broader XML cleanup work.

## Summary

| Area | Count |
|---|---:|
| Production XML factory references | ${xml_factory_usage} |
| Direct DocumentBuilderFactory.newInstance calls | ${direct_document_builder_new_instance} |
| Direct TransformerFactory.newInstance calls | ${direct_transformer_new_instance} |
| SecureXmlFactory runtime calls | ${secure_factory_usage} |

## Required runtime hardening points

| File | Expected state |
|---|---|
| \`delosdb-engine/src/main/java/org/apache/derby/iapi/xml/SecureXmlFactory.java\` | central helper present |
| \`delosdb-engine/src/main/java/org/apache/derby/iapi/types/SqlXmlUtil.java\` | uses hardened parser and transformer factories |
| \`delosdb-engine/src/main/java/org/apache/derby/vti/XmlVTI.java\` | uses hardened parser factory |
| \`delosdb-buildtools/src/main/java/org/apache/derbyBuild/SecureXmlFactoryProbe.java\` | probes external entity blocking |
EOF_REPORT

write_matches "Production direct DocumentBuilderFactory.newInstance calls" 'DocumentBuilderFactory[.]newInstance[[:space:]]*\(' "${existing_roots[@]}"
write_matches "Production direct TransformerFactory.newInstance calls" 'TransformerFactory[.]newInstance[[:space:]]*\(' "${existing_roots[@]}"
write_matches "Production SecureXmlFactory calls" 'SecureXmlFactory[.]new(DocumentBuilderFactory|TransformerFactory)' "${existing_roots[@]}"
write_matches "Production XML factory references" 'DocumentBuilderFactory|SAXParserFactory|XMLInputFactory|TransformerFactory|SecureXmlFactory' "${existing_roots[@]}"

if [[ "$VERIFY" == true ]]; then
  failed=false

  for file in "$secure_factory_file" "$sql_xml_util_file" "$xml_vti_file" "$probe_file"; do
    if [[ ! -f "$file" ]]; then
      echo "XML hardening audit failed: required file missing: ${file#${ROOT_DIR}/}" >&2
      failed=true
    fi
  done

  if [[ -f "$secure_factory_file" ]]; then
    for token in \
      'FEATURE_SECURE_PROCESSING' \
      'external-general-entities' \
      'external-parameter-entities' \
      'load-external-dtd' \
      'ACCESS_EXTERNAL_DTD' \
      'ACCESS_EXTERNAL_SCHEMA' \
      'ACCESS_EXTERNAL_STYLESHEET' \
      'setXIncludeAware(false)' \
      'setExpandEntityReferences(false)'; do
      if ! grep -q "$token" "$secure_factory_file"; then
        echo "XML hardening audit failed: SecureXmlFactory missing token: $token" >&2
        failed=true
      fi
    done
  fi

  if [[ -f "$sql_xml_util_file" ]] && ! grep -q 'SecureXmlFactory.newDocumentBuilderFactory(false, true)' "$sql_xml_util_file"; then
    echo "XML hardening audit failed: SqlXmlUtil does not use the hardened parser factory." >&2
    failed=true
  fi

  if [[ -f "$sql_xml_util_file" ]] && ! grep -q 'SecureXmlFactory.newTransformerFactory()' "$sql_xml_util_file"; then
    echo "XML hardening audit failed: SqlXmlUtil does not use the hardened transformer factory." >&2
    failed=true
  fi

  if [[ -f "$xml_vti_file" ]] && ! grep -q 'SecureXmlFactory.newDocumentBuilderFactory(false, false)' "$xml_vti_file"; then
    echo "XML hardening audit failed: XmlVTI does not use the hardened parser factory." >&2
    failed=true
  fi

  if [[ -f "$probe_file" ]] && ! grep -q 'External XML entity was expanded' "$probe_file"; then
    echo "XML hardening audit failed: SecureXmlFactoryProbe does not assert XXE blocking." >&2
    failed=true
  fi

  if [[ "$failed" == true ]]; then
    echo "See $REPORT_FILE" >&2
    exit 1
  fi
fi

echo "XML hardening audit written to $REPORT_FILE"
