/*

   Derby - Class org.apache.derby.iapi.services.classfile.GeneratedBytecodeVersionExperimentProbe

   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to you under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

 */

package org.apache.derby.iapi.services.classfile;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.Locale;

import org.apache.derby.iapi.util.ByteArray;

/**
 * Test-only classfile-version experiment for Derby's inherited bytecode writer.
 *
 * <p>The production writer still emits the version in {@link VMDescriptor}. This
 * probe deliberately overrides the package-protected {@link ClassHolder}
 * version fields in a build-tool class so DelosDB can check whether Java 21 can
 * define and execute a tiny Derby-written classfile at candidate legacy targets.
 * It is not a runtime feature and it must not be used as a production version
 * switch.</p>
 */
public final class GeneratedBytecodeVersionExperimentProbe {

    private static final int CLASSFILE_MAGIC = 0xCAFEBABE;

    private GeneratedBytecodeVersionExperimentProbe() {
    }

    public static void main(String[] args) throws Exception {
        int[] majors = args.length == 0 ? new int[] {45, 49, 50} : parseMajors(args);

        System.out.println("# Generated bytecode classfile-version experiment");
        System.out.println();
        System.out.println("writer=org.apache.derby.iapi.services.classfile.ClassHolder");
        System.out.println("productionMajor=" + VMDescriptor.JAVA_CLASS_FORMAT_MAJOR_VERSION);
        System.out.println("productionMinor=" + VMDescriptor.JAVA_CLASS_FORMAT_MINOR_VERSION);
        System.out.println("candidateMajors=" + join(majors));
        System.out.println();

        for (int major : majors) {
            int minor = major == VMDescriptor.JAVA_CLASS_FORMAT_MAJOR_VERSION
                    ? VMDescriptor.JAVA_CLASS_FORMAT_MINOR_VERSION
                    : 0;
            CandidateResult result = defineAndInvokeCandidate(major, minor);
            System.out.println("candidate.major=" + result.major);
            System.out.println("candidate.minor=" + result.minor);
            System.out.println("candidate.magic=" + String.format(Locale.ROOT, "0x%08X", result.magic));
            System.out.println("candidate.byteLength=" + result.byteLength);
            System.out.println("candidate.defined=" + result.defined);
            System.out.println("candidate.invokeValue=" + result.invokeValue);
            System.out.println();

            if (result.magic != CLASSFILE_MAGIC) {
                throw new IllegalStateException("Unexpected classfile magic for major " + major);
            }
            if (result.major != major || result.minor != minor) {
                throw new IllegalStateException("Classfile header mismatch for major " + major);
            }
            if (!result.defined || result.invokeValue != 42) {
                throw new IllegalStateException("Candidate major " + major + " did not define and execute");
            }
        }
    }

    private static CandidateResult defineAndInvokeCandidate(int major, int minor) throws Exception {
        String className = "org.apache.derby.exe.GeneratedBytecodeVersionExperimentV" + major;
        ClassHolder holder = new ClassHolder(className, "java/lang/Object", Modifier.PUBLIC);
        holder.major_version = major;
        holder.minor_version = minor;
        addStaticValueMethod(holder);

        ByteArray bytecode = holder.getFileFormat();
        byte[] bytes = bytecode.getArray();
        int offset = bytecode.getOffset();
        int magic = u4(bytes, offset);
        int actualMinor = u2(bytes, offset + 4);
        int actualMajor = u2(bytes, offset + 6);

        CandidateLoader loader = new CandidateLoader();
        Class<?> candidate = loader.define(className, bytecode);
        Method value = candidate.getMethod("value");
        int invokeValue = ((Integer) value.invoke(null)).intValue();

        return new CandidateResult(actualMajor, actualMinor, magic, bytecode.getLength(), true, invokeValue);
    }

    /** Add {@code public static int value() { return 42; }} without StackMapTable. */
    private static void addStaticValueMethod(ClassHolder holder) throws Exception {
        ClassMember method = holder.addMember("value", "()I", Modifier.PUBLIC | Modifier.STATIC);
        ClassFormatOutput code = new ClassFormatOutput(32);
        code.putU2(1);       // max_stack
        code.putU2(0);       // max_locals
        code.putU4(3);       // code_length
        code.putU1(0x10);    // bipush
        code.putU1(42);      // 42
        code.putU1(0xac);    // ireturn
        code.putU2(0);       // exception_table_length
        code.putU2(0);       // attributes_count; intentionally no StackMapTable
        method.addAttribute("Code", code);
    }

    private static int[] parseMajors(String[] args) {
        int[] majors = new int[args.length];
        for (int i = 0; i < args.length; i++) {
            majors[i] = Integer.parseInt(args[i]);
        }
        return majors;
    }

    private static String join(int[] majors) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < majors.length; i++) {
            if (i > 0) {
                builder.append(',');
            }
            builder.append(majors[i]);
        }
        return builder.toString();
    }

    private static int u2(byte[] bytes, int offset) {
        return ((bytes[offset] & 0xff) << 8) | (bytes[offset + 1] & 0xff);
    }

    private static int u4(byte[] bytes, int offset) {
        return (u2(bytes, offset) << 16) | u2(bytes, offset + 2);
    }

    private static final class CandidateLoader extends ClassLoader {
        Class<?> define(String className, ByteArray bytecode) {
            return defineClass(className,
                    bytecode.getArray(),
                    bytecode.getOffset(),
                    bytecode.getLength());
        }
    }

    private static final class CandidateResult {
        final int major;
        final int minor;
        final int magic;
        final int byteLength;
        final boolean defined;
        final int invokeValue;

        CandidateResult(int major, int minor, int magic, int byteLength,
                boolean defined, int invokeValue) {
            this.major = major;
            this.minor = minor;
            this.magic = magic;
            this.byteLength = byteLength;
            this.defined = defined;
            this.invokeValue = invokeValue;
        }
    }
}
