package delosdb.smoke;

import org.apache.derby.impl.sql.execute.DelosTableScanProviderLookup;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Optional;

/**
 * Phase F3.1 proof: the generated Derby table-scan path reaches
 * GenericResultSetFactory.getTableScanResultSet(...), and that factory seam can
 * resolve persisted provider metadata for a delos_mvcc table without changing
 * FromBaseTable.generate(), AsmJava, or the generated bytecode call shape.
 */
public final class StoragePhaseF3FactoryBranchSmoke {
    private static final String DATABASE_PATH = "storage-phase-f3-factory-branch-db";
    private static final String TABLE_NAME = "F3_FACTORY_BRANCH_MVCC";
    private static final String PROVIDER_NAME = "delos_mvcc";

    private StoragePhaseF3FactoryBranchSmoke() {
    }

    public static void main(String[] args) throws Exception {
        SmokeUtils.loadEmbeddedDriver();

        try {
            createNativeDerbyTableAndRow();
            SmokeUtils.shutdown(DATABASE_PATH);
            proveFactoryBranchAfterRestart();
        } finally {
            System.clearProperty(DelosTableScanProviderLookup.FACTORY_PROBE_PROPERTY);
            SmokeUtils.shutdown(DATABASE_PATH);
        }

        System.out.println("storage_phase_f3_factory_branch: PASS");
    }

    private static void createNativeDerbyTableAndRow() throws Exception {
        try (Connection connection = SmokeUtils.connect(DATABASE_PATH, true)) {
            executePrepared(connection,
                    "CREATE TABLE " + TABLE_NAME + " (id INT, value VARCHAR(32)) USING delos_mvcc");
            executePrepared(connection,
                    "INSERT INTO " + TABLE_NAME + " VALUES (1, 'alpha')");
        }
    }

    private static void proveFactoryBranchAfterRestart() throws Exception {
        try (Connection connection = SmokeUtils.connect(DATABASE_PATH, false)) {
            DelosTableScanProviderLookup.resetFactoryLookupForTesting();
            System.setProperty(DelosTableScanProviderLookup.FACTORY_PROBE_PROPERTY, "true");

            try (PreparedStatement statement = connection.prepareStatement(
                    "SELECT id, value FROM " + TABLE_NAME + " WHERE id = ?")) {
                statement.setInt(1, 1);
                try (ResultSet rows = statement.executeQuery()) {
                    require(rows.next(), "Expected native Derby SELECT to return the inserted proof row");
                    require(rows.getInt(1) == 1, "Unexpected id from native Derby SELECT");
                    require("alpha".equals(rows.getString(2)), "Unexpected value from native Derby SELECT");
                    require(!rows.next(), "Expected one proof row from native Derby SELECT");
                }
            }

            require(DelosTableScanProviderLookup.factoryLookupCountForTesting() > 0,
                    "Expected GenericResultSetFactory table-scan branch probe to observe at least one lookup");

            Optional<DelosTableScanProviderLookup.Result> observed =
                    DelosTableScanProviderLookup.lastNonDefaultFactoryLookupForTesting();
            require(observed.isPresent(),
                    "Expected GenericResultSetFactory table-scan branch probe to observe a non-default provider");
            DelosTableScanProviderLookup.Result result = observed.get();
            require(PROVIDER_NAME.equals(result.storageProviderName()),
                    "Expected factory branch provider " + PROVIDER_NAME + " but was "
                            + result.storageProviderName());
            require(TABLE_NAME.equals(result.tableName()),
                    "Expected factory branch table " + TABLE_NAME + " but was " + result.tableName());
            require(result.isProvider(PROVIDER_NAME),
                    "Expected factory branch observation to identify delos_mvcc provider");
        }
    }

    private static void executePrepared(Connection connection, String sql) throws Exception {
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.executeUpdate();
        }
    }

    private static void require(boolean condition, String message) {
        if (!condition) {
            throw new IllegalStateException(message);
        }
    }
}
