/*

   Derby - Class org.apache.derbyBuild.asm.AsmMethodBuilderParity

   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to you under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

 */

package org.apache.derbyBuild.asm;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Proxy;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.List;
import org.apache.derby.iapi.services.cache.CacheManager;
import org.apache.derby.iapi.services.cache.Cacheable;
import org.apache.derby.iapi.services.classfile.VMOpcode;
import org.apache.derby.iapi.services.compiler.ClassBuilder;
import org.apache.derby.iapi.services.compiler.JavaFactory;
import org.apache.derby.iapi.services.compiler.LocalField;
import org.apache.derby.iapi.services.compiler.MethodBuilder;
import org.apache.derby.iapi.services.loader.ClassFactory;
import org.apache.derby.iapi.services.loader.GeneratedClass;
import org.apache.derby.iapi.util.ByteArray;
import org.apache.derby.impl.services.bytecode.BCJava;
import org.apache.derby.shared.common.error.StandardException;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Behavior parity proof for a small, explicit subset of Derby's existing
 * JavaFactory/ClassBuilder/MethodBuilder contracts. The reference side uses
 * Derby's current BCJava backend. The candidate side uses an inactive ASM
 * implementation. This task is not wired into the engine runtime path.
 */
public final class AsmMethodBuilderParity {
    private static final String GENERATED_PACKAGE = "org.apache.derbyBuild.asm.generated.";

    private AsmMethodBuilderParity() {
    }

    public static void main(String[] args) throws Exception {
        JavaFactory bcJava = bootlessBcJava();
        JavaFactory asmJava = new ParityAsmJavaFactory();

        List<ParityCase> cases = List.of(
                new ConstantsCase(),
                new ParametersCase(),
                new FieldsCase(),
                new StaticCallCase(),
                new BooleanConditionalCase(),
                new NullConditionalCase(),
                new CastInstanceOfCase());

        List<String> passed = new ArrayList<>();
        for (ParityCase parityCase : cases) {
            Class<?> bcClass = buildAndLoad(bcJava, "Bc" + parityCase.name(), parityCase);
            Class<?> asmClass = buildAndLoad(asmJava, "Asm" + parityCase.name(), parityCase);
            parityCase.verify(bcClass, asmClass);
            passed.add(parityCase.name());
        }

        System.out.println("ASM MethodBuilder parity passed: " + String.join(", ", passed));
    }

    private static Class<?> buildAndLoad(JavaFactory javaFactory, String className, ParityCase parityCase)
            throws Exception {
        ClassBuilder classBuilder = javaFactory.newClassBuilder(
                null,
                GENERATED_PACKAGE,
                Modifier.PUBLIC,
                className,
                "java.lang.Object");
        addDefaultConstructor(classBuilder);
        parityCase.build(classBuilder);
        byte[] classBytes = byteArray(classBuilder.getClassBytecode());
        assertReadableClassfile(classBytes, classBuilder.getFullName());
        return new ParityClassLoader().define(classBuilder.getFullName(), classBytes);
    }

    private static void addDefaultConstructor(ClassBuilder classBuilder) {
        MethodBuilder constructor = classBuilder.newConstructorBuilder(Modifier.PUBLIC);
        constructor.callSuper();
        constructor.methodReturn();
        constructor.complete();
    }

    private static void assertReadableClassfile(byte[] classBytes, String expectedName) {
        if (classBytes.length < 8) {
            throw new AssertionError("Generated classfile is too small: " + classBytes.length);
        }
        int magic = ((classBytes[0] & 0xff) << 24)
                | ((classBytes[1] & 0xff) << 16)
                | ((classBytes[2] & 0xff) << 8)
                | (classBytes[3] & 0xff);
        if (magic != 0xcafebabe) {
            throw new AssertionError("Generated bytes do not start with CAFEBABE");
        }
        String actualName = new ClassReader(classBytes).getClassName().replace('/', '.');
        if (!expectedName.equals(actualName)) {
            throw new AssertionError("ClassReader saw " + actualName + " instead of " + expectedName);
        }
    }

    private static byte[] byteArray(ByteArray byteArray) {
        byte[] result = new byte[byteArray.getLength()];
        System.arraycopy(byteArray.getArray(), byteArray.getOffset(), result, 0, byteArray.getLength());
        return result;
    }

    private static JavaFactory bootlessBcJava() throws Exception {
        BCJava bcJava = new BCJava();
        Field cacheField = BCJava.class.getDeclaredField("vmTypeIdCache");
        cacheField.setAccessible(true);
        cacheField.set(bcJava, bootlessTypeCache());
        return bcJava;
    }

    private static CacheManager bootlessTypeCache() {
        InvocationHandler handler = (Object proxy, Method method, Object[] args) -> {
            String methodName = method.getName();
            if ("find".equals(methodName) || "findCached".equals(methodName)) {
                return newVmTypeIdCacheable(args[0]);
            }
            if ("release".equals(methodName)) {
                return null;
            }
            if (method.getReturnType().equals(Boolean.TYPE)) {
                return false;
            }
            if (method.getReturnType().equals(Integer.TYPE)) {
                return 0;
            }
            if (method.getReturnType().equals(Long.TYPE)) {
                return 0L;
            }
            if ("toString".equals(methodName)) {
                return "BootlessBCJavaTypeCache";
            }
            throw new UnsupportedOperationException("Bootless BCJava type cache does not implement " + methodName);
        };
        return (CacheManager) Proxy.newProxyInstance(
                AsmMethodBuilderParity.class.getClassLoader(),
                new Class<?>[] {CacheManager.class},
                handler);
    }

    private static Cacheable newVmTypeIdCacheable(Object key) throws Exception {
        Class<?> type = Class.forName("org.apache.derby.impl.services.bytecode.VMTypeIdCacheable");
        java.lang.reflect.Constructor<?> constructor = type.getDeclaredConstructor();
        constructor.setAccessible(true);
        Object cacheable = constructor.newInstance();
        Method setIdentity = type.getDeclaredMethod("setIdentity", Object.class);
        setIdentity.setAccessible(true);
        return (Cacheable) setIdentity.invoke(cacheable, key);
    }

    private interface ParityCase {
        String name();

        void build(ClassBuilder classBuilder) throws Exception;

        void verify(Class<?> bcClass, Class<?> asmClass) throws Exception;
    }

    private static final class ConstantsCase implements ParityCase {
        @Override
        public String name() {
            return "Constants";
        }

        @Override
        public void build(ClassBuilder classBuilder) {
            MethodBuilder intValue = classBuilder.newMethodBuilder(Modifier.PUBLIC | Modifier.STATIC, "int", "intValue");
            intValue.push(12345);
            intValue.methodReturn();
            intValue.complete();

            MethodBuilder longValue = classBuilder.newMethodBuilder(Modifier.PUBLIC | Modifier.STATIC, "long", "longValue");
            longValue.push(9876543210L);
            longValue.methodReturn();
            longValue.complete();

            MethodBuilder stringValue = classBuilder.newMethodBuilder(Modifier.PUBLIC | Modifier.STATIC, "java.lang.String", "stringValue");
            stringValue.push("asm-parity");
            stringValue.methodReturn();
            stringValue.complete();
        }

        @Override
        public void verify(Class<?> bcClass, Class<?> asmClass) throws Exception {
            assertSameResult(bcClass, asmClass, "intValue");
            assertSameResult(bcClass, asmClass, "longValue");
            assertSameResult(bcClass, asmClass, "stringValue");
        }
    }

    private static final class ParametersCase implements ParityCase {
        @Override
        public String name() {
            return "Parameters";
        }

        @Override
        public void build(ClassBuilder classBuilder) {
            MethodBuilder echoInt = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC | Modifier.STATIC,
                    "int",
                    "echoInt",
                    new String[] {"int"});
            echoInt.getParameter(0);
            echoInt.methodReturn();
            echoInt.complete();

            MethodBuilder echoLong = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC | Modifier.STATIC,
                    "long",
                    "echoLong",
                    new String[] {"long"});
            echoLong.getParameter(0);
            echoLong.methodReturn();
            echoLong.complete();

            MethodBuilder secondWideSlot = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC | Modifier.STATIC,
                    "int",
                    "secondWideSlot",
                    new String[] {"long", "int"});
            secondWideSlot.getParameter(1);
            secondWideSlot.methodReturn();
            secondWideSlot.complete();
        }

        @Override
        public void verify(Class<?> bcClass, Class<?> asmClass) throws Exception {
            assertSameResult(bcClass, asmClass, "echoInt", new Class<?>[] {int.class}, 7);
            assertSameResult(bcClass, asmClass, "echoLong", new Class<?>[] {long.class}, 10L);
            assertSameResult(bcClass, asmClass, "secondWideSlot", new Class<?>[] {long.class, int.class}, 10L, 99);
        }
    }

    private static final class FieldsCase implements ParityCase {
        @Override
        public String name() {
            return "Fields";
        }

        @Override
        public void build(ClassBuilder classBuilder) {
            LocalField value = classBuilder.addField("java.lang.String", "value", Modifier.PRIVATE);

            MethodBuilder store = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC,
                    "void",
                    "store",
                    new String[] {"java.lang.String"});
            store.getParameter(0);
            store.setField(value);
            store.methodReturn();
            store.complete();

            MethodBuilder load = classBuilder.newMethodBuilder(Modifier.PUBLIC, "java.lang.String", "load");
            load.getField(value);
            load.methodReturn();
            load.complete();
        }

        @Override
        public void verify(Class<?> bcClass, Class<?> asmClass) throws Exception {
            Object bc = bcClass.getDeclaredConstructor().newInstance();
            Object asm = asmClass.getDeclaredConstructor().newInstance();
            bcClass.getMethod("store", String.class).invoke(bc, "stored-value");
            asmClass.getMethod("store", String.class).invoke(asm, "stored-value");
            Object bcValue = bcClass.getMethod("load").invoke(bc);
            Object asmValue = asmClass.getMethod("load").invoke(asm);
            assertEquals("Fields.load", bcValue, asmValue);
        }
    }

    private static final class StaticCallCase implements ParityCase {
        @Override
        public String name() {
            return "StaticCall";
        }

        @Override
        public void build(ClassBuilder classBuilder) {
            MethodBuilder boxed = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC | Modifier.STATIC,
                    "java.lang.Integer",
                    "boxed",
                    new String[] {"int"});
            boxed.getParameter(0);
            boxed.callMethod(VMOpcode.INVOKESTATIC, "java.lang.Integer", "valueOf", "java.lang.Integer", 1);
            boxed.methodReturn();
            boxed.complete();
        }

        @Override
        public void verify(Class<?> bcClass, Class<?> asmClass) throws Exception {
            assertSameResult(bcClass, asmClass, "boxed", new Class<?>[] {int.class}, 42);
        }
    }

    private static final class BooleanConditionalCase implements ParityCase {
        @Override
        public String name() {
            return "BooleanConditional";
        }

        @Override
        public void build(ClassBuilder classBuilder) {
            MethodBuilder choose = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC | Modifier.STATIC,
                    "int",
                    "choose",
                    new String[] {"boolean"});
            choose.getParameter(0);
            choose.conditionalIf();
            choose.push(10);
            choose.startElseCode();
            choose.push(20);
            choose.completeConditional();
            choose.methodReturn();
            choose.complete();
        }

        @Override
        public void verify(Class<?> bcClass, Class<?> asmClass) throws Exception {
            assertSameResult(bcClass, asmClass, "choose", new Class<?>[] {boolean.class}, true);
            assertSameResult(bcClass, asmClass, "choose", new Class<?>[] {boolean.class}, false);
        }
    }

    private static final class NullConditionalCase implements ParityCase {
        @Override
        public String name() {
            return "NullConditional";
        }

        @Override
        public void build(ClassBuilder classBuilder) {
            MethodBuilder choose = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC | Modifier.STATIC,
                    "int",
                    "choose",
                    new String[] {"java.lang.Object"});
            choose.getParameter(0);
            choose.conditionalIfNull();
            choose.push(1);
            choose.startElseCode();
            choose.push(2);
            choose.completeConditional();
            choose.methodReturn();
            choose.complete();
        }

        @Override
        public void verify(Class<?> bcClass, Class<?> asmClass) throws Exception {
            assertSameResult(bcClass, asmClass, "choose", new Class<?>[] {Object.class}, new Object[] {null});
            assertSameResult(bcClass, asmClass, "choose", new Class<?>[] {Object.class}, "not-null");
        }
    }

    private static final class CastInstanceOfCase implements ParityCase {
        @Override
        public String name() {
            return "CastInstanceOf";
        }

        @Override
        public void build(ClassBuilder classBuilder) {
            MethodBuilder isString = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC | Modifier.STATIC,
                    "boolean",
                    "isString",
                    new String[] {"java.lang.Object"});
            isString.getParameter(0);
            isString.isInstanceOf("java.lang.String");
            isString.methodReturn();
            isString.complete();

            MethodBuilder castString = classBuilder.newMethodBuilder(
                    Modifier.PUBLIC | Modifier.STATIC,
                    "java.lang.String",
                    "castString",
                    new String[] {"java.lang.Object"});
            castString.getParameter(0);
            castString.cast("java.lang.String");
            castString.methodReturn();
            castString.complete();
        }

        @Override
        public void verify(Class<?> bcClass, Class<?> asmClass) throws Exception {
            assertSameResult(bcClass, asmClass, "isString", new Class<?>[] {Object.class}, "abc");
            assertSameResult(bcClass, asmClass, "isString", new Class<?>[] {Object.class}, Integer.valueOf(1));
            assertSameResult(bcClass, asmClass, "castString", new Class<?>[] {Object.class}, "cast-ok");
        }
    }

    private static void assertSameResult(Class<?> bcClass, Class<?> asmClass, String methodName) throws Exception {
        assertSameResult(bcClass, asmClass, methodName, new Class<?>[0]);
    }

    private static void assertSameResult(Class<?> bcClass, Class<?> asmClass, String methodName,
            Class<?>[] parameterTypes, Object... args) throws Exception {
        Object bcValue = bcClass.getMethod(methodName, parameterTypes).invoke(null, args);
        Object asmValue = asmClass.getMethod(methodName, parameterTypes).invoke(null, args);
        assertEquals(methodName, bcValue, asmValue);
    }

    private static void assertEquals(String label, Object expected, Object actual) {
        if (expected == null ? actual != null : !expected.equals(actual)) {
            throw new AssertionError(label + " mismatch: expected=" + expected + " actual=" + actual);
        }
    }

    private static final class ParityClassLoader extends ClassLoader {
        private Class<?> define(String name, byte[] bytes) {
            return defineClass(name, bytes, 0, bytes.length);
        }
    }

    private static final class ParityAsmJavaFactory implements JavaFactory {
        @Override
        public ClassBuilder newClassBuilder(ClassFactory cf, String packageName, int modifiers, String className,
                String superClass) {
            return new ParityAsmClassBuilder(packageName, modifiers, className, superClass);
        }
    }

    private static final class ParityAsmClassBuilder implements ClassBuilder {
        private final String className;
        private final String fullName;
        private final String internalName;
        private final String superClass;
        private final ClassWriter classWriter;
        private final List<ParityAsmMethodBuilder> methods = new ArrayList<>();
        private boolean hasConstructor;
        private byte[] classBytes;

        private ParityAsmClassBuilder(String packageName, int modifiers, String className, String superClass) {
            String safePackageName = packageName == null ? "" : packageName;
            this.className = className;
            this.fullName = safePackageName + className;
            this.internalName = internalName(this.fullName);
            this.superClass = superClass == null ? "java.lang.Object" : superClass;
            this.classWriter = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
            classWriter.visit(Opcodes.V21, modifiers, internalName, null, internalName(this.superClass), null);
        }

        @Override
        public LocalField addField(String type, String name, int modifiers) {
            ParityAsmLocalField field = new ParityAsmLocalField(internalName, type, name, descriptor(type));
            classWriter.visitField(modifiers, name, field.descriptor(), null, null).visitEnd();
            return field;
        }

        @Override
        public GeneratedClass getGeneratedClass() throws StandardException {
            throw new UnsupportedOperationException("ASM-2 parity proof does not wire classes into Derby ClassFactory");
        }

        @Override
        public ByteArray getClassBytecode() throws StandardException {
            if (classBytes == null) {
                if (!hasConstructor) {
                    ParityAsmMethodBuilder constructor = newConstructor(Modifier.PUBLIC, new String[0]);
                    constructor.callSuper();
                    constructor.methodReturn();
                    constructor.complete();
                }
                for (ParityAsmMethodBuilder method : methods) {
                    if (!method.isComplete()) {
                        throw new IllegalStateException("Method " + method.getName() + " was not completed");
                    }
                }
                classWriter.visitEnd();
                classBytes = classWriter.toByteArray();
            }
            return new ByteArray(classBytes);
        }

        @Override
        public String getName() {
            return className;
        }

        @Override
        public String getFullName() {
            return fullName;
        }

        @Override
        public MethodBuilder newMethodBuilder(int modifiers, String returnType, String methodName) {
            return newMethodBuilder(modifiers, returnType, methodName, new String[0]);
        }

        @Override
        public MethodBuilder newMethodBuilder(int modifiers, String returnType, String methodName, String[] parms) {
            ParityAsmMethodBuilder method = new ParityAsmMethodBuilder(this, modifiers, returnType, methodName, parms);
            methods.add(method);
            return method;
        }

        @Override
        public MethodBuilder newConstructorBuilder(int modifiers) {
            return newConstructor(modifiers, new String[0]);
        }

        private ParityAsmMethodBuilder newConstructor(int modifiers, String[] parms) {
            hasConstructor = true;
            ParityAsmMethodBuilder method = new ParityAsmMethodBuilder(this, modifiers, null, "<init>", parms);
            methods.add(method);
            return method;
        }

        private MethodVisitor visitMethod(int modifiers, String returnType, String methodName, String[] parms) {
            return classWriter.visitMethod(modifiers, methodName, methodDescriptor(returnType, parms), null, null);
        }
    }

    private record ParityAsmLocalField(String ownerInternalName, String type, String name, String descriptor)
            implements LocalField {
    }

    private record MethodDescriptor(short opcode, String declaringClass, String methodName, String returnType) {
    }

    private static final class ConditionalState {
        private final Label elseLabel = new Label();
        private final Label endLabel = new Label();
    }

    private static final class ParityAsmMethodBuilder implements MethodBuilder {
        private final ParityAsmClassBuilder owner;
        private final String name;
        private final String returnType;
        private final String[] parameterTypes;
        private final boolean isStatic;
        private final MethodVisitor mv;
        private final List<String> stackTypes = new ArrayList<>();
        private final Deque<String> pendingNewTypes = new ArrayDeque<>();
        private final Deque<ConditionalState> conditionals = new ArrayDeque<>();
        private boolean complete;

        private ParityAsmMethodBuilder(ParityAsmClassBuilder owner, int modifiers, String returnType, String name,
                String[] parameterTypes) {
            this.owner = owner;
            this.name = name;
            this.returnType = returnType == null ? "void" : returnType;
            this.parameterTypes = parameterTypes == null ? new String[0] : parameterTypes.clone();
            this.isStatic = Modifier.isStatic(modifiers);
            this.mv = owner.visitMethod(modifiers, this.returnType, name, this.parameterTypes);
            this.mv.visitCode();
        }

        @Override
        public void addThrownException(String exceptionClass) {
            throw unsupported("addThrownException");
        }

        @Override
        public String getName() {
            return name;
        }

        @Override
        public void complete() {
            if (!complete) {
                mv.visitMaxs(0, 0);
                mv.visitEnd();
                complete = true;
            }
        }

        private boolean isComplete() {
            return complete;
        }

        @Override
        public void getParameter(int id) {
            int slot = isStatic ? 0 : 1;
            for (int i = 0; i < id; i++) {
                slot += localSlotWidth(parameterTypes[i]);
            }
            String parameterType = parameterTypes[id];
            mv.visitVarInsn(loadOpcode(parameterType), slot);
            pushType(parameterType);
        }

        @Override
        public void push(byte value) {
            push((int) value);
            replaceTopType("byte");
        }

        @Override
        public void push(boolean value) {
            mv.visitInsn(value ? Opcodes.ICONST_1 : Opcodes.ICONST_0);
            pushType("boolean");
        }

        @Override
        public void push(short value) {
            push((int) value);
            replaceTopType("short");
        }

        @Override
        public void push(int value) {
            switch (value) {
                case -1 -> mv.visitInsn(Opcodes.ICONST_M1);
                case 0 -> mv.visitInsn(Opcodes.ICONST_0);
                case 1 -> mv.visitInsn(Opcodes.ICONST_1);
                case 2 -> mv.visitInsn(Opcodes.ICONST_2);
                case 3 -> mv.visitInsn(Opcodes.ICONST_3);
                case 4 -> mv.visitInsn(Opcodes.ICONST_4);
                case 5 -> mv.visitInsn(Opcodes.ICONST_5);
                default -> {
                    if (value >= Byte.MIN_VALUE && value <= Byte.MAX_VALUE) {
                        mv.visitIntInsn(Opcodes.BIPUSH, value);
                    } else if (value >= Short.MIN_VALUE && value <= Short.MAX_VALUE) {
                        mv.visitIntInsn(Opcodes.SIPUSH, value);
                    } else {
                        mv.visitLdcInsn(value);
                    }
                }
            }
            pushType("int");
        }

        @Override
        public void push(long value) {
            if (value == 0L) {
                mv.visitInsn(Opcodes.LCONST_0);
            } else if (value == 1L) {
                mv.visitInsn(Opcodes.LCONST_1);
            } else {
                mv.visitLdcInsn(value);
            }
            pushType("long");
        }

        @Override
        public void push(float value) {
            if (value == 0.0f) {
                mv.visitInsn(Opcodes.FCONST_0);
            } else if (value == 1.0f) {
                mv.visitInsn(Opcodes.FCONST_1);
            } else if (value == 2.0f) {
                mv.visitInsn(Opcodes.FCONST_2);
            } else {
                mv.visitLdcInsn(value);
            }
            pushType("float");
        }

        @Override
        public void push(double value) {
            if (value == 0.0d) {
                mv.visitInsn(Opcodes.DCONST_0);
            } else if (value == 1.0d) {
                mv.visitInsn(Opcodes.DCONST_1);
            } else {
                mv.visitLdcInsn(value);
            }
            pushType("double");
        }

        @Override
        public void push(String value) {
            if (value == null) {
                mv.visitInsn(Opcodes.ACONST_NULL);
                pushType("java.lang.String");
            } else {
                mv.visitLdcInsn(value);
                pushType("java.lang.String");
            }
        }

        @Override
        public void pushNull(String className) {
            mv.visitInsn(Opcodes.ACONST_NULL);
            pushType(className);
        }

        @Override
        public void getField(LocalField field) {
            ParityAsmLocalField asmField = asmField(field);
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitFieldInsn(Opcodes.GETFIELD, asmField.ownerInternalName(), asmField.name(), asmField.descriptor());
            pushType(asmField.type());
        }

        @Override
        public void getField(String declaringClass, String fieldName, String fieldType) {
            popType();
            mv.visitFieldInsn(Opcodes.GETFIELD, internalName(declaringClass), fieldName, descriptor(fieldType));
            pushType(fieldType);
        }

        @Override
        public void getStaticField(String declaringClass, String fieldName, String fieldType) {
            mv.visitFieldInsn(Opcodes.GETSTATIC, internalName(declaringClass), fieldName, descriptor(fieldType));
            pushType(fieldType);
        }

        @Override
        public void setField(LocalField field) {
            ParityAsmLocalField asmField = asmField(field);
            popType();
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitInsn(Opcodes.SWAP);
            mv.visitFieldInsn(Opcodes.PUTFIELD, asmField.ownerInternalName(), asmField.name(), asmField.descriptor());
        }

        @Override
        public void putField(LocalField field) {
            ParityAsmLocalField asmField = asmField(field);
            String valueType = popType();
            mv.visitInsn(Opcodes.DUP);
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitInsn(Opcodes.SWAP);
            mv.visitFieldInsn(Opcodes.PUTFIELD, asmField.ownerInternalName(), asmField.name(), asmField.descriptor());
            pushType(valueType);
        }

        @Override
        public void putField(String fieldName, String fieldType) {
            String valueType = popType();
            mv.visitInsn(Opcodes.DUP);
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitInsn(Opcodes.SWAP);
            mv.visitFieldInsn(Opcodes.PUTFIELD, owner.internalName, fieldName, descriptor(fieldType));
            pushType(valueType);
        }

        @Override
        public void putField(String declaringClass, String fieldName, String fieldType) {
            String valueType = popType();
            popType();
            mv.visitInsn(Opcodes.DUP_X1);
            mv.visitFieldInsn(Opcodes.PUTFIELD, internalName(declaringClass), fieldName, descriptor(fieldType));
            pushType(valueType);
        }

        @Override
        public void pushNewStart(String className) {
            mv.visitTypeInsn(Opcodes.NEW, internalName(className));
            mv.visitInsn(Opcodes.DUP);
            pendingNewTypes.push(className);
        }

        @Override
        public void pushNewComplete(int numArgs) {
            String className = pendingNewTypes.pop();
            String[] argumentTypes = popArgumentTypes(numArgs);
            mv.visitMethodInsn(Opcodes.INVOKESPECIAL, internalName(className), "<init>", methodDescriptor("void", argumentTypes), false);
            pushType(className);
        }

        @Override
        public void pushNewArray(String className, int size) {
            push(size);
            popType();
            if (isPrimitive(className)) {
                mv.visitIntInsn(Opcodes.NEWARRAY, newArrayType(className));
            } else {
                mv.visitTypeInsn(Opcodes.ANEWARRAY, internalName(className));
            }
            pushType(className + "[]");
        }

        @Override
        public void pushThis() {
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            pushType(owner.fullName);
        }

        @Override
        public void upCast(String className) {
            replaceTopType(className);
        }

        @Override
        public void cast(String className) {
            String current = popType();
            if (!isPrimitive(className)) {
                mv.visitTypeInsn(Opcodes.CHECKCAST, internalName(className));
                pushType(className);
                return;
            }
            if (!current.equals(className)) {
                castPrimitive(current, className);
            }
            pushType(className);
        }

        @Override
        public void isInstanceOf(String className) {
            popType();
            mv.visitTypeInsn(Opcodes.INSTANCEOF, internalName(className));
            pushType("boolean");
        }

        @Override
        public void pop() {
            String type = popType();
            mv.visitInsn(localSlotWidth(type) == 2 ? Opcodes.POP2 : Opcodes.POP);
        }

        @Override
        public void endStatement() {
            if (!stackTypes.isEmpty()) {
                pop();
            }
        }

        @Override
        public void methodReturn() {
            if (!"void".equals(returnType)) {
                popType();
            }
            mv.visitInsn(returnOpcode(returnType));
        }

        @Override
        public void conditionalIfNull() {
            popType();
            ConditionalState conditional = new ConditionalState();
            conditionals.push(conditional);
            mv.visitJumpInsn(Opcodes.IFNONNULL, conditional.elseLabel);
        }

        @Override
        public void conditionalIf() {
            popType();
            ConditionalState conditional = new ConditionalState();
            conditionals.push(conditional);
            mv.visitJumpInsn(Opcodes.IFEQ, conditional.elseLabel);
        }

        @Override
        public void startElseCode() {
            ConditionalState conditional = conditionals.peek();
            mv.visitJumpInsn(Opcodes.GOTO, conditional.endLabel);
            mv.visitLabel(conditional.elseLabel);
        }

        @Override
        public void completeConditional() {
            ConditionalState conditional = conditionals.pop();
            mv.visitLabel(conditional.endLabel);
        }

        @Override
        public int callMethod(short type, String declaringClass, String methodName, String returnType, int numArgs) {
            String[] argumentTypes = popArgumentTypes(numArgs);
            String ownerType = declaringClass;
            if (type != VMOpcode.INVOKESTATIC) {
                String receiverType = popType();
                if (ownerType == null) {
                    ownerType = receiverType;
                }
            }
            String methodDescriptor = methodDescriptor(returnType, argumentTypes);
            int opcode = switch (type) {
                case VMOpcode.INVOKESTATIC -> Opcodes.INVOKESTATIC;
                case VMOpcode.INVOKEVIRTUAL -> Opcodes.INVOKEVIRTUAL;
                case VMOpcode.INVOKESPECIAL -> Opcodes.INVOKESPECIAL;
                case VMOpcode.INVOKEINTERFACE -> Opcodes.INVOKEINTERFACE;
                default -> throw new IllegalArgumentException("Unsupported invocation opcode: " + type);
            };
            mv.visitMethodInsn(opcode, internalName(ownerType), methodName, methodDescriptor, opcode == Opcodes.INVOKEINTERFACE);
            if (!"void".equals(returnType)) {
                pushType(returnType);
            }
            return localSlotWidth(returnType);
        }

        @Override
        public Object describeMethod(short opcode, String declaringClass, String methodName, String returnType) {
            return new MethodDescriptor(opcode, declaringClass, methodName, returnType);
        }

        @Override
        public int callMethod(Object methodDescriptor) {
            MethodDescriptor descriptor = (MethodDescriptor) methodDescriptor;
            return callMethod(descriptor.opcode(), descriptor.declaringClass(), descriptor.methodName(), descriptor.returnType(), 0);
        }

        @Override
        public void callSuper() {
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitMethodInsn(Opcodes.INVOKESPECIAL, internalName(owner.superClass), "<init>", "()V", false);
        }

        @Override
        public void getArrayElement(int element) {
            String arrayType = popType();
            String elementType = elementType(arrayType);
            push(element);
            mv.visitInsn(arrayLoadOpcode(elementType));
            pushType(elementType);
        }

        @Override
        public void setArrayElement(int element) {
            String valueType = popType();
            String arrayType = popType();
            push(element);
            mv.visitInsn(Opcodes.SWAP);
            mv.visitInsn(arrayStoreOpcode(valueType));
            if (!elementType(arrayType).equals(valueType) && !isIntLike(elementType(arrayType), valueType)) {
                throw new IllegalStateException("Array element type mismatch: " + arrayType + " value=" + valueType);
            }
        }

        @Override
        public void swap() {
            String valueB = popType();
            String valueA = popType();
            mv.visitInsn(Opcodes.SWAP);
            pushType(valueB);
            pushType(valueA);
        }

        @Override
        public void dup() {
            String top = peekType();
            mv.visitInsn(localSlotWidth(top) == 2 ? Opcodes.DUP2 : Opcodes.DUP);
            pushType(top);
        }

        @Override
        public boolean statementNumHitLimit(int noStatementsAdded) {
            return false;
        }

        private String[] popArgumentTypes(int numArgs) {
            String[] argumentTypes = new String[numArgs];
            for (int i = numArgs - 1; i >= 0; i--) {
                argumentTypes[i] = popType();
            }
            return argumentTypes;
        }

        private void pushType(String type) {
            stackTypes.add(type);
        }

        private String popType() {
            if (stackTypes.isEmpty()) {
                throw new IllegalStateException("ASM parity stack underflow in " + name);
            }
            return stackTypes.remove(stackTypes.size() - 1);
        }

        private String peekType() {
            if (stackTypes.isEmpty()) {
                throw new IllegalStateException("ASM parity stack underflow in " + name);
            }
            return stackTypes.get(stackTypes.size() - 1);
        }

        private void replaceTopType(String type) {
            popType();
            pushType(type);
        }

        private UnsupportedOperationException unsupported(String operation) {
            return new UnsupportedOperationException("ASM-2 parity MethodBuilder does not implement " + operation + " yet");
        }
    }

    private static ParityAsmLocalField asmField(LocalField field) {
        if (!(field instanceof ParityAsmLocalField asmField)) {
            throw new IllegalArgumentException("Unsupported LocalField implementation: " + field.getClass().getName());
        }
        return asmField;
    }

    private static String methodDescriptor(String returnType, String[] parameters) {
        StringBuilder descriptor = new StringBuilder("(");
        if (parameters != null) {
            for (String parameter : parameters) {
                descriptor.append(descriptor(parameter));
            }
        }
        descriptor.append(')').append(returnType == null ? "V" : descriptor(returnType));
        return descriptor.toString();
    }

    private static String descriptor(String type) {
        return switch (type) {
            case "void" -> "V";
            case "boolean" -> "Z";
            case "byte" -> "B";
            case "char" -> "C";
            case "short" -> "S";
            case "int" -> "I";
            case "long" -> "J";
            case "float" -> "F";
            case "double" -> "D";
            default -> {
                if (type.endsWith("[]")) {
                    yield '[' + descriptor(type.substring(0, type.length() - 2));
                }
                if (type.startsWith("[")) {
                    yield type.replace('.', '/');
                }
                yield 'L' + internalName(type) + ';';
            }
        };
    }

    private static String internalName(String className) {
        return className.replace('.', '/');
    }

    private static int loadOpcode(String type) {
        return switch (type) {
            case "boolean", "byte", "char", "short", "int" -> Opcodes.ILOAD;
            case "long" -> Opcodes.LLOAD;
            case "float" -> Opcodes.FLOAD;
            case "double" -> Opcodes.DLOAD;
            default -> Opcodes.ALOAD;
        };
    }

    private static int returnOpcode(String type) {
        return switch (type) {
            case "void" -> Opcodes.RETURN;
            case "boolean", "byte", "char", "short", "int" -> Opcodes.IRETURN;
            case "long" -> Opcodes.LRETURN;
            case "float" -> Opcodes.FRETURN;
            case "double" -> Opcodes.DRETURN;
            default -> Opcodes.ARETURN;
        };
    }

    private static int localSlotWidth(String type) {
        return ("long".equals(type) || "double".equals(type)) ? 2 : 1;
    }

    private static boolean isPrimitive(String type) {
        return switch (type) {
            case "void", "boolean", "byte", "char", "short", "int", "long", "float", "double" -> true;
            default -> false;
        };
    }

    private static boolean isIntLike(String expected, String actual) {
        return isIntLike(expected) && isIntLike(actual);
    }

    private static boolean isIntLike(String type) {
        return switch (type) {
            case "boolean", "byte", "char", "short", "int" -> true;
            default -> false;
        };
    }

    private static void castPrimitive(String from, String to) {
        throw new UnsupportedOperationException("ASM-2 parity does not implement primitive cast " + from + " -> " + to);
    }

    private static int newArrayType(String type) {
        return switch (type) {
            case "boolean" -> Opcodes.T_BOOLEAN;
            case "byte" -> Opcodes.T_BYTE;
            case "char" -> Opcodes.T_CHAR;
            case "short" -> Opcodes.T_SHORT;
            case "int" -> Opcodes.T_INT;
            case "long" -> Opcodes.T_LONG;
            case "float" -> Opcodes.T_FLOAT;
            case "double" -> Opcodes.T_DOUBLE;
            default -> throw new IllegalArgumentException("Not a primitive array type: " + type);
        };
    }

    private static String elementType(String arrayType) {
        if (!arrayType.endsWith("[]")) {
            throw new IllegalArgumentException("Not a Java array type: " + arrayType);
        }
        return arrayType.substring(0, arrayType.length() - 2);
    }

    private static int arrayLoadOpcode(String elementType) {
        return switch (elementType) {
            case "boolean", "byte" -> Opcodes.BALOAD;
            case "char" -> Opcodes.CALOAD;
            case "short" -> Opcodes.SALOAD;
            case "int" -> Opcodes.IALOAD;
            case "long" -> Opcodes.LALOAD;
            case "float" -> Opcodes.FALOAD;
            case "double" -> Opcodes.DALOAD;
            default -> Opcodes.AALOAD;
        };
    }

    private static int arrayStoreOpcode(String elementType) {
        return switch (elementType) {
            case "boolean", "byte" -> Opcodes.BASTORE;
            case "char" -> Opcodes.CASTORE;
            case "short" -> Opcodes.SASTORE;
            case "int" -> Opcodes.IASTORE;
            case "long" -> Opcodes.LASTORE;
            case "float" -> Opcodes.FASTORE;
            case "double" -> Opcodes.DASTORE;
            default -> Opcodes.AASTORE;
        };
    }
}
