/*

   Derby - Class org.apache.derbyBuild.GeneratedBytecodeVersionProbe

   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to you under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

 */

package org.apache.derbyBuild;

import java.lang.reflect.Modifier;
import java.util.Locale;

import org.apache.derby.iapi.services.classfile.ClassHolder;
import org.apache.derby.iapi.services.classfile.VMDescriptor;
import org.apache.derby.iapi.util.ByteArray;

/**
 * Emits and checks the classfile header produced by Derby's inherited
 * ClassHolder bytecode writer.
 *
 * <p>This is a proof tool, not a runtime feature. It gives DelosDB a small,
 * repeatable JVM-21 modernization guardrail before anyone changes the
 * generated-class version constants.</p>
 */
public final class GeneratedBytecodeVersionProbe {

    private static final int CLASSFILE_MAGIC = 0xCAFEBABE;

    private GeneratedBytecodeVersionProbe() {
    }

    public static void main(String[] args) throws Exception {
        ClassHolder holder = new ClassHolder(
                "org.apache.derby.exe.GeneratedBytecodeVersionProbeClass",
                "java/lang/Object",
                Modifier.PUBLIC);

        ByteArray bytecode = holder.getFileFormat();
        byte[] bytes = bytecode.getArray();
        int offset = bytecode.getOffset();

        int magic = u4(bytes, offset);
        int minor = u2(bytes, offset + 4);
        int major = u2(bytes, offset + 6);

        System.out.println("# Generated bytecode classfile header probe");
        System.out.println();
        System.out.println("writer=org.apache.derby.iapi.services.classfile.ClassHolder");
        System.out.println("magic=" + String.format(Locale.ROOT, "0x%08X", magic));
        System.out.println("minor=" + minor);
        System.out.println("major=" + major);
        System.out.println("vmDescriptorMinor=" + VMDescriptor.JAVA_CLASS_FORMAT_MINOR_VERSION);
        System.out.println("vmDescriptorMajor=" + VMDescriptor.JAVA_CLASS_FORMAT_MAJOR_VERSION);
        System.out.println("byteLength=" + bytecode.getLength());

        if (magic != CLASSFILE_MAGIC) {
            throw new IllegalStateException("Unexpected classfile magic: " + magic);
        }
        if (minor != VMDescriptor.JAVA_CLASS_FORMAT_MINOR_VERSION) {
            throw new IllegalStateException(
                    "Emitted minor version " + minor
                    + " does not match VMDescriptor "
                    + VMDescriptor.JAVA_CLASS_FORMAT_MINOR_VERSION);
        }
        if (major != VMDescriptor.JAVA_CLASS_FORMAT_MAJOR_VERSION) {
            throw new IllegalStateException(
                    "Emitted major version " + major
                    + " does not match VMDescriptor "
                    + VMDescriptor.JAVA_CLASS_FORMAT_MAJOR_VERSION);
        }
    }

    private static int u2(byte[] bytes, int offset) {
        return ((bytes[offset] & 0xff) << 8) | (bytes[offset + 1] & 0xff);
    }

    private static int u4(byte[] bytes, int offset) {
        return (u2(bytes, offset) << 16) | u2(bytes, offset + 2);
    }
}
